/**
 * ÍNDICE DE VERIFICAÇÕES
 * Re-exporta todas as verificações organizadas por domínio
 */
// Verificações básicas
export {
    esperarMensagemSucesso as verificarMensagemSucesso,
    verificarAlerta,
    esperarTextoVisivel,
    esperarElementoVisivel,
    esperarElementoInvisivel,
    esperarBotaoVisivel,
    verificarUrl,
    esperarUrl,
    verificarUrlDoPainel,
    verificarModalVisivel,
    verificarModalFechado,
    esperarNotificacaoLoginInvalido,
    verificarDisponibilizacaoConcluida,
    verificarModalDisponibilizacaoVisivel,
    verificarCampoObservacoesValor,
    verificarBotaoDisponibilizarHabilitado,
    verificarBotaoDisponibilizarDesabilitado
} from './verificacoes-basicas';

// Verificações de processo
export {
    verificarPaginaEdicaoProcesso,
    verificarPaginaCadastroProcesso,
    verificarCamposObrigatoriosFormulario,
    verificarNotificacaoErro,
    aguardarProcessoNoPainel,
    verificarProcessoEditado,
    verificarDialogoConfirmacaoRemocao,
    verificarAceiteRegistradoComSucesso,
    verificarCadastroDevolvidoComSucesso,
    verificarProcessoRemovidoComSucesso,
    verificarModalFinalizacaoProcesso,
    verificarModalFinalizacaoFechado,
    verificarFinalizacaoBloqueada,
    verificarProcessoFinalizadoNoPainel,
    verificarMensagemFinalizacaoSucesso,
    verificarMapasVigentesNotificacao,
    verificarEmailFinalizacaoEnviado,
    verificarBotaoFinalizarProcessoVisivel,
    verificarBotaoFinalizarProcessoInvisivel,
    verificarDialogoConfirmacaoFechado,
    verificarProcessoIniciadoComSucesso,
    verificarPermanenciaFormularioEdicao,
    verificarConfirmacaoInicializacao,
    verificarModalConfirmacaoInicializacao,
    verificarProcessoInicializadoComSucesso,
    verificarValorCampoDescricao,
    verificarBotaoIniciarProcessoVisivel,
    verificarModalConfirmacaoIniciarProcessoVisivel,
    verificarModalConfirmacaoIniciarProcessoInvisivel,
    verificarPermanenciaNaPaginaProcesso,
    verificarModalConfirmacaoIniciacaoProcesso,
    verificarProcessoBloqueadoParaEdicao,
    aguardarTabelaProcessosCarregada,
    verificarQuantidadeProcessosNaTabela,
    verificarBotaoRemoverVisivel,
    verificarBotaoRemoverInvisivel,
    verificarCheckboxUnidadeMarcado,
    verificarValorCampoDataLimite,
    verificarCampoTipoVisivel,
    verificarCampoTipoValor,
    verificarProcessoNaoVisivel,
    verificarPaginaDetalheProcesso,
    verificarCriacaoSubprocessos,
    verificarCamposProcessoDesabilitados,
    verificarSituacaoProcesso,
    verificarBotaoIniciarProcessoInvisivel,
    verificarMapaVazioCriadoParaSubprocesso,
    verificarMovimentacaoInicialSubprocesso,
    verificarAlertaInicioProcesso
} from './verificacoes-processo';

// Verificações de UI
export {
    verificarElementosPainel,
    verificarPaginaLogin,
    verificarPainelBasico,
    verificarPainelSemCriacao,
    verificarPainelComCriacao,
    verificarPainelComAlertas,
    verificarAusenciaBotaoCriarProcesso,
    verificarProcessoVisivel,
    verificarProcessoInvisivel,
    verificarSelecaoArvoreCheckboxes,
    verificarComportamentoMarcacaoCheckbox,
    verificarComportamentoCheckboxInteroperacional,
    verificarTituloProcessos,
    verificarElementosDetalhesProcessoVisiveis,
    verificarCamposLogin,
    verificarEstruturaAdmin,
    verificarEstruturaServidor,
    verificarPaginaCadastroAtividades,
    verificarBotaoImpactoVisivel,
    verificarModalImportacaoVisivel,
    verificarBotaoDisponibilizarVisivel,
    verificarAtividadeVisivel,
    verificarAtividadeNaoVisivel,
    verificarConhecimentoVisivel,
    verificarConhecimentoVisivelNoCard,
    verificarConhecimentoNaoVisivel,
    verificarContadorAtividades,
    verificarColunasTabelaAlertas,
    verificarAlertasOrdenadosPorDataHora,
    verificarBotaoHistoricoAnaliseVisivel,
    verificarModalHistoricoAnalise,
    verificarModalHistoricoAnaliseAberto,
    verificarModalHistoricoAnaliseVazio,
    verificarModalHistoricoAnaliseComRegistros,
    verificarAcoesAnaliseGestor,
    verificarAcaoHomologarVisivel,
    verificarMensagemNenhumImpacto,
    verificarModalImpactosAberto,
    verificarModalImpactosFechado,
    verificarCompetenciaVisivel,
    verificarCompetenciaNaoVisivel,
    verificarListagemAtividadesEConhecimentos,
    verificarModoSomenteLeitura,
    verificarCabecalhoUnidade,
    verificarAtividadesAssociadas,
    verificarDescricaoCompetencia,
    verificarPainelVisivel,
    verificarSelecaoPerfilVisivel,
    verificarImpactosNoMapa,
    verificarCardAcaoVisivel,
    verificarCardAcaoInvisivel,
    verificarPainelAdminVisivel,
    verificarPainelChefeVisivel,
    verificarAlertaNaTabela
} from './verificacoes-ui';

export * from './verificacoes-atividades';
