services:
  db:
    image: postgres:15-alpine
    container_name: sgc-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: sgc-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "10000:10000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres

volumes:
  postgres_data: