export const SELETORES = {
    // Títulos e tabelas
    TITULO_PROCESSOS: 'titulo-processos',
    TITULO_ALERTAS: 'titulo-alertas',
    TABELA_PROCESSOS: 'tabela-processos',
    TABELA_ALERTAS: 'tabela-alertas',
    COLUNA_DESCRICAO: 'coluna-descricao',
    COLUNA_TIPO: 'coluna-tipo',
    COLUNA_UNIDADES: 'coluna-unidades',
    COLUNA_SITUACAO: 'coluna-situacao',

    // Botões globais / ações de processo
    BTN_CRIAR_PROCESSO: 'btn-criar-processo',
    BTN_INICIAR_PROCESSO: 'btn-iniciar-processo',
    BTN_SALVAR: 'btn-salvar',
    BTN_CANCELAR: 'btn-cancelar',
    BTN_CONFIRMAR: 'btn-confirmar',
    BTN_FECHAR: 'btn-fechar',
    // Test-ids específicos para modais e ações críticas
    BTN_MODAL_FECHAR: 'btn-modal-fechar',
    BTN_DISPONIBILIZAR: 'btn-disponibilizar',
    BTN_DISPONIBILIZAR_PAGE: 'btn-disponibilizar-page',
    BTN_REGISTRAR_ACEITE: 'btn-registrar-aceite',
    BTN_DEVOLVER: 'btn-devolver',
    BTN_HOMOLOGAR: 'btn-homologar',
    BTN_VALIDAR: 'btn-validar',
    BTN_ENTRAR: 'btn-entrar',
    BTN_CRIAR: 'btn-criar',
    BTN_EDITAR: 'btn-editar',
    BTN_EXCLUIR: 'btn-excluir',
    BTN_ACEITAR: 'btn-aceitar',
    BTN_VER_SUGESTOES: 'btn-ver-sugestoes',
    BTN_HISTORICO_ANALISE: 'historico-analise-btn',
    // Ações adicionais usadas em modais/fluxos
    BTN_IMPORTAR: 'btn-importar',
    BTN_LIMPAR_NOTIFICACOES: 'btn-limpar-notificacoes',
    BTN_VER_EMAIL: 'btn-ver-email',

    // Cabeçalhos e componentes
    SUBPROCESSO_HEADER: 'subprocesso-header',
    PROCESSO_INFO: 'processo-info',
    UNIDADE_CARD: 'unidade-card',
    LINHA_TABELA_ARVORE: '[data-testid^=tree-table-row-]',
    TREE_TABLE_ROW: '[data-testid^="tree-table-row-"]',
    MAPA_CARD: 'mapa-card',
    BLOCO_COMPETENCIA: 'competencia-block',

    // Atividades / conhecimentos
    ITEM_ATIVIDADE: 'atividade-item',
    ITEM_CONHECIMENTO: 'conhecimento-item',
    BADGE_CONHECIMENTOS: 'badge-conhecimentos',
    ATIVIDADE_NAO_ASSOCIADA: 'atividade-nao-associada',

    // Competências (actions)
    EDITAR_COMPETENCIA: 'btn-editar-competencia',
    EXCLUIR_COMPETENCIA: 'btn-excluir-competencia',

    // Inputs e botões de criação/edição
    INFO_UNIDADE: 'unidade-info',
    INPUT_NOVA_ATIVIDADE: 'input-nova-atividade',
    BTN_ADICIONAR_ATIVIDADE: 'btn-adicionar-atividade',
    INPUT_NOVO_CONHECIMENTO: 'input-novo-conhecimento',
    BTN_ADICIONAR_CONHECIMENTO: 'btn-adicionar-conhecimento',
    BTN_EDITAR_ATIVIDADE: 'btn-editar-atividade',
    BTN_REMOVER_ATIVIDADE: 'btn-remover-atividade',
    BTN_EDITAR_CONHECIMENTO: 'btn-editar-conhecimento',
    BTN_REMOVER_CONHECIMENTO: 'btn-remover-conhecimento',
    INPUT_EDITAR_ATIVIDADE: 'input-editar-atividade',
    INPUT_EDITAR_CONHECIMENTO: 'input-editar-conhecimento',
    BTN_SALVAR_EDICAO_ATIVIDADE: 'btn-salvar-edicao-atividade',
    BTN_CANCELAR_EDICAO_ATIVIDADE: 'btn-cancelar-edicao-atividade',
    BTN_SALVAR_EDICAO_CONHECIMENTO: 'btn-salvar-edicao-conhecimento',
    BTN_CANCELAR_EDICAO_CONHECIMENTO: 'btn-cancelar-edicao-conhecimento',

    // Modais e observações (sugestões para novos test-ids a serem adicionados na UI)
    MODAL_APRESENTAR_SUGESTOES: 'modal-apresentar-sugestoes',
    MODAL_VALIDAR: 'modal-validar',
    MODAL_DEVOLUCAO: 'modal-devolucao',
    MODAL_HISTORICO: 'modal-historico',
    INPUT_OBSERVACAO_DEVOLUCAO: 'input-observacao-devolucao',
    INPUT_OBSERVACAO_VALIDACAO: 'input-observacao-validacao',
    // Inputs e selects utilizados em modais importantes
    INPUT_DATA_LIMITE: 'input-data-limite',
    INPUT_OBSERVACOES: 'input-observacoes',
    INPUT_NOVA_DATA_LIMITE: 'input-nova-data-limite',
    INPUT_DESCRICAO_COMPETENCIA: 'input-descricao-competencia',
    SELECT_PROCESSO: 'select-processo',
    SELECT_UNIDADE: 'select-unidade',
    BTN_MODAL_CONFIRMAR: 'btn-modal-confirmar',
    BTN_MODAL_CANCELAR: 'btn-modal-cancelar',
    // Novas chaves para o Grupo 2
    BTN_ACAO_PRINCIPAL_ANALISE: 'btn-acao-principal-analise',
    BTN_MODAL_CONFIRMAR_ACEITE: 'btn-modal-confirmar-aceite',
    BTN_MODAL_CONFIRMAR_DEVOLUCAO: 'btn-modal-confirmar-devolucao',
    BTN_REGISTRAR_ACEITE_HOMOLOGAR: 'btn-registrar-aceite-homologar',
    BTN_ABRIR_MODAL_HOMOLOGAR_BLOCO: 'btn-abrir-modal-homologar-bloco',
    BTN_CONFIRMAR_ACAO_BLOCO: 'btn-confirmar-acao-bloco',
} as const;

export const TEXTOS = {
    SISTEMA_GESTAO_COMPETENCIAS: 'Sistema de Gestão de Competências',
    ENTRAR: 'Entrar',
    CRIAR_PROCESSO: 'Criar processo',
    SALVAR: 'Salvar',
    INICIAR_PROCESSO: 'Iniciar processo',
    PROCESSO_INICIADO: 'Processo iniciado',
    PREENCHA_CAMPOS_UNIDADES: 'Preencha todos os campos e selecione ao menos uma unidade.',
    ERRO_CAMPOS_OBRIGATORIOS: 'Preencha todos os campos e selecione ao menos uma unidade.',
    DADOS_INCOMPLETOS: 'Dados incompletos',
    FINALIZAR_PROCESSO: 'Finalizar processo',
    PROCESSO_FINALIZADO: 'Processo finalizado',
    FINALIZACAO_BLOQUEADA: 'Não é possível encerrar o processo enquanto houver unidades com mapa de competência ainda não homologado',
    DETALHES_PROCESSO: 'Detalhes do processo',
    DETALHES_SUBPROCESSO: 'Detalhes do subprocesso',
    CADASTRO_ATIVIDADES_CONHECIMENTOS: 'Atividades e conhecimentos',
    ADICIONAR_ATIVIDADE: 'Adicionar atividade',
    ADICIONAR_CONHECIMENTO: 'Adicionar conhecimento',
    EDITAR: 'Editar',
    REMOVER: 'Remover',
    CONFIRMAR: 'Confirmar',
    CANCELAR: 'Cancelar',
    FECHAR: 'Fechar',
    DEVOLVER: 'Devolver',
    DISPONIBILIZAR: 'Disponibilizar',
    DEVOLVER_PARA_AJUSTES: 'Devolver para ajustes',
    REGISTRAR_ACEITE: 'Registrar aceite',
    HISTORICO_ANALISE: 'Histórico de análise',
    ACEITE_REVISAO_TITULO: 'Aceite da revisão do cadastro',
    MAPA_COMPETENCIAS: 'Mapa de competências',
    CRIAR_COMPETENCIA: 'Criar competência',
    IMPACTO_NO_MAPA: 'Impacto no mapa',
    IMPORTAR_ATIVIDADES: 'Importar atividades',
    FINALIZACAO_PROCESSO: 'Finalização de processo',
    CONFIRMA_FINALIZACAO: 'Confirma a finalização do processo',
    CONFIRMACAO_VIGENCIA_MAPAS: 'Essa ação tornará vigentes os mapas de competências homologados',
    MAPAS_VIGENTES: 'mapas de competências estão agora vigentes',
    EMAIL_ENVIADO: 'E-mail enviado',
    UNIDADES_PARTICIPANTES: 'Unidades participantes',
    SITUACAO_LABEL: 'Situação:',
    EM_ANDAMENTO: 'Em andamento',
    FINALIZADO: 'Finalizado',
    NAO_INICIADO: 'Não iniciado',
    CONFIRMACAO_INICIAR_PROCESSO: 'Ao iniciar o processo, não será mais possível editá-lo ou removê-lo',
    NOTIFICACAO_EMAIL: 'todas as unidades participantes serão notificadas por e-mail',
    COLUNA_DATA_HORA: 'Data/Hora',
    COLUNA_DESCRICAO: 'Descrição',
    COLUNA_PROCESSO: 'Processo',
    COLUNA_ORIGEM: 'Origem',
    MAPA_COMPETENCIAS_TECNICAS: 'Mapa de competências técnicas',
    HOMOLOGAR: 'Homologar',
    VALIDAR: 'Validar',
    ERRO_LOGIN_INVALIDO: 'Título ou senha inválidos.',
    USUARIO_NAO_ENCONTRADO: 'Usuário não encontrado',
    ERRO_DESCRICAO_OBRIGATORIA: 'Preencha a descrição',
    ERRO_UNIDADE_SEM_MAPA: 'Não é possível incluir em processos de revisão ou diagnóstico, unidades que ainda não passaram por processo de mapeamento.',
    PROCESSO_CRIADO: 'Processo criado.',
    PROCESSO_ALTERADO: 'Processo alterado.',
    CONFIRMACAO_REMOCAO_PROCESSO_INICIO: 'Remover o processo \'',
    CONFIRMACAO_REMOCAO_PROCESSO_FIM: '\'? Esta ação não poderá ser desfeita.',
    PROCESSO_REMOVIDO_INICIO: 'Processo ',
    PROCESSO_REMOVIDO_FIM: ' removido',
    TITULO_PROCESSOS_LABEL: 'Processos',
    CADASTRO_DEVOLVIDO_AJUSTES: 'O cadastro foi devolvido para ajustes!',
    ANALISE_REGISTRADA_SUCESSO: 'A análise foi registrada com sucesso!',
    ACEITE_REGISTRADO: 'Aceite registrado',
    CADASTRO_HOMOLOGADO_SUCESSO: 'O cadastro foi homologado com sucesso!',
    // Novos textos para modal de disponibilização
    DISPONIBILACAO_TITULO: 'Disponibilização do mapa de competências',
    LABEL_DATA_LIMITE: 'Data limite para validação',
    LABEL_OBSERVACOES: 'Observações'
} as const;

export const URLS = {
    PAINEL: '/painel',
    LOGIN: '/login',
    PROCESSO_CADASTRO: '/processo/cadastro',
    PROCESSO_DETALHE: '/processo/',
    SUBPROCESSO: '/processo/',
    VISUALIZACAO_MAPA: '/vis-mapa',
} as const;

export const ROTULOS = {
    DESCRICAO: 'Descrição',
    TIPO: 'Tipo',
    DATA_LIMITE: 'Data limite',
    NOVA_ATIVIDADE: 'Nova atividade',
    NOVO_CONHECIMENTO: 'Novo conhecimento',
    EDITAR_ATIVIDADE: 'Editar atividade',
    SUGESTOES: 'sugestões',
    OBSERVACOES: 'observações',
    OBSERVACAO: 'observação',
    TITULO_ELEITORAL: 'Título eleitoral',
    SENHA: 'Senha',
    PERFIL_UNIDADE: 'Perfil - Unidade',
} as const;

export const DADOS_TESTE = {
    PROCESSOS: {
        MAPEAMENTO_STIC: {id: 1, unidade: 'STIC'},
        REVISAO_STIC: {id: 2, unidade: 'STIC'},
        TESTE_FINALIZACAO: {id: 99, nome: 'Processo teste para finalização'},
        TESTE_MAPEAMENTO: {id: 101, nome: 'Processo teste mapeamento para finalização'},
        TESTE_REVISAO: {id: 102, nome: 'Processo teste revisão para finalização'},

    },
    UNIDADES: {
        STIC: 'STIC',
        SESEL: 'SESEL',
        SEDIA: 'SEDIA',
        SEMARE: 'SEMARE',
        SEDOC: 'SEDOC',
    },
    PERFIS: {
        ADMIN: {idServidor: '6', perfil: 'ADMIN', unidade: 'SEDOC'},
        GESTOR: {idServidor: '1', perfil: 'GESTOR', unidade: 'SESEL'},
        CHEFE: {idServidor: '14', perfil: 'CHEFE', unidade: 'STIC'},
        CHEFE_SEDIA: {idServidor: '14', perfil: 'CHEFE', unidade: 'SEDIA'},
        SERVIDOR: {idServidor: '15', perfil: 'SERVIDOR', unidade: 'STIC'},
    },
} as const;

export const SELETORES_CSS = {
    MODAL_VISIVEL: '.modal.show',
    NOTIFICACAO_SUCESSO: '.notification-success',
    NOTIFICACAO_EMAIL: '.notification-email',
    NOTIFICACAO_ERRO: '.notification-error',
    CARD_ATIVIDADE: '.atividade-card',
    GRUPO_CONHECIMENTO: '.group-conhecimento',
    LINHA_TABELA: 'table tbody tr',
    CHECKBOX: 'input[type="checkbox"]',
    CHECKBOX_MARCADO: 'input[type="checkbox"]:checked',
    TITULO_CADASTRO_PROCESSO: 'h2:has-text("Cadastro de processo")',
    TITULO_MODAL_INICIAR_PROCESSO: 'h5:has-text("Iniciar processo")',
    CAMPO_DESCRICAO: '#descricao',
    CAMPO_TIPO: '#tipo',
    CAMPO_DATA_LIMITE: '#dataLimite',
    CHECKBOX_STIC: '#chk-STIC',
} as const;