export const SELETORES = {
    TITULO_PROCESSOS: 'titulo-processos',
    TITULO_ALERTAS: 'titulo-alertas',
    TABELA_PROCESSOS: 'tabela-processos',
    TABELA_ALERTAS: 'tabela-alertas',
    COLUNA_DESCRICAO: 'coluna-descricao',
    COLUNA_TIPO: 'coluna-tipo',
    COLUNA_UNIDADES: 'coluna-unidades',
    COLUNA_SITUACAO: 'coluna-situacao',
    BTN_CRIAR_PROCESSO: 'btn-criar-processo',
    BTN_INICIAR_PROCESSO: 'btn-iniciar-processo',
    SUBPROCESSO_HEADER: 'subprocesso-header',
    PROCESSO_INFO: 'processo-info',
    UNIDADE_CARD: 'unidade-card',
    LINHA_TABELA_ARVORE: '[data-testid^=tree-table-row-]',
    TREE_TABLE_ROW: '[data-testid^="tree-table-row-"]',
    MAPA_CARD: 'mapa-card',
    BLOCO_COMPETENCIA: 'competencia-block',
    ITEM_ATIVIDADE: 'atividade-item',
    ITEM_CONHECIMENTO: 'conhecimento-item',
    EDITAR_COMPETENCIA: 'editar-competencia',
    EXCLUIR_COMPETENCIA: 'excluir-competencia',
    BADGE_CONHECIMENTOS: 'badge-conhecimentos',
    ATIVIDADE_NAO_ASSOCIADA: 'atividade-nao-associada',
    INFO_UNIDADE: 'unidade-info',
    INPUT_NOVA_ATIVIDADE: 'input-nova-atividade',
    BTN_ADICIONAR_ATIVIDADE: 'btn-adicionar-atividade',
    INPUT_NOVO_CONHECIMENTO: 'input-novo-conhecimento',
    BTN_ADICIONAR_CONHECIMENTO: 'btn-adicionar-conhecimento',
    BTN_EDITAR_ATIVIDADE: 'btn-editar-atividade',
    BTN_REMOVER_ATIVIDADE: 'btn-remover-atividade',
    BTN_EDITAR_CONHECIMENTO: 'btn-editar-conhecimento',
    BTN_REMOVER_CONHECIMENTO: 'btn-remover-conhecimento',
    INPUT_EDITAR_ATIVIDADE: 'input-editar-atividade',
    INPUT_EDITAR_CONHECIMENTO: 'input-editar-conhecimento',
    BTN_SALVAR_EDICAO_ATIVIDADE: 'btn-salvar-edicao-atividade',
    BTN_CANCELAR_EDICAO_ATIVIDADE: 'btn-cancelar-edicao-atividade',
    BTN_SALVAR_EDICAO_CONHECIMENTO: 'btn-salvar-edicao-conhecimento',
    BTN_CANCELAR_EDICAO_CONHECIMENTO: 'btn-cancelar-edicao-conhecimento',
} as const;

export const TEXTOS = {
    SISTEMA_GESTAO_COMPETENCIAS: 'Sistema de Gestão de Competências',
    ENTRAR: 'Entrar',
    CRIAR_PROCESSO: 'Criar processo',
    SALVAR: 'Salvar',
    INICIAR_PROCESSO: 'Iniciar processo',
    PROCESSO_INICIADO: 'Processo iniciado',
    PREENCHA_CAMPOS_UNIDADES: 'Preencha todos os campos e selecione ao menos uma unidade.',
    ERRO_CAMPOS_OBRIGATORIOS: 'Preencha todos os campos e selecione ao menos uma unidade.',
    DADOS_INCOMPLETOS: 'Dados incompletos',
    FINALIZAR_PROCESSO: 'Finalizar processo',
    PROCESSO_FINALIZADO: 'Processo finalizado',
    DETALHES_PROCESSO: 'Detalhes do processo',
    DETALHES_SUBPROCESSO: 'Detalhes do subprocesso',
    CADASTRO_ATIVIDADES_CONHECIMENTOS: 'Atividades e conhecimentos',
    ADICIONAR_ATIVIDADE: 'Adicionar atividade',
    ADICIONAR_CONHECIMENTO: 'Adicionar conhecimento',
    EDITAR: 'Editar',
    REMOVER: 'Remover',
    CONFIRMAR: 'Confirmar',
    CANCELAR: 'Cancelar',
    DEVOLVER: 'Devolver',
    DISPONIBILIZAR: 'Disponibilizar',
    MAPA_COMPETENCIAS: 'Mapa de competências',
    CRIAR_COMPETENCIA: 'Criar competência',
    IMPACTO_NO_MAPA: 'Impacto no mapa',
    IMPORTAR_ATIVIDADES: 'Importar atividades',
    FINALIZACAO_PROCESSO: 'Finalização de processo',
    CONFIRMA_FINALIZACAO: 'Confirma a finalização do processo',
    MAPAS_VIGENTES: 'mapas de competências estão agora vigentes',
    EMAIL_ENVIADO: 'E-mail enviado',
    UNIDADES_PARTICIPANTES: 'Unidades participantes',
    SITUACAO_LABEL: 'Situação:',
    EM_ANDAMENTO: 'Em andamento',
    FINALIZADO: 'Finalizado',
    NAO_INICIADO: 'Não iniciado',
    CONFIRMACAO_INICIAR_PROCESSO: 'Ao iniciar o processo, não será mais possível editá-lo ou removê-lo',
    NOTIFICACAO_EMAIL: 'todas as unidades participantes serão notificadas por e-mail',
    COLUNA_DATA_HORA: 'Data/Hora',
    COLUNA_DESCRICAO: 'Descrição',
    COLUNA_PROCESSO: 'Processo',
    COLUNA_ORIGEM: 'Origem',
    MAPA_COMPETENCIAS_TECNICAS: 'Mapa de competências técnicas',
    HOMOLOGAR: 'Homologar',
    VALIDAR: 'Validar',
    ERRO_LOGIN_INVALIDO: 'Título ou senha inválidos.',
    USUARIO_NAO_ENCONTRADO: 'Usuário não encontrado',
    ERRO_DESCRICAO_OBRIGATORIA: 'Preencha a descrição',
    ERRO_UNIDADE_SEM_MAPA: 'Não é possível incluir em processos de revisão ou diagnóstico, unidades que ainda não passaram por processo de mapeamento.',
    PROCESSO_CRIADO: 'Processo criado.',
    PROCESSO_ALTERADO: 'Processo alterado.',
    CONFIRMACAO_REMOCAO_PROCESSO_INICIO: 'Remover o processo \'',
    CONFIRMACAO_REMOCAO_PROCESSO_FIM: '\'? Esta ação não poderá ser desfeita.',
    PROCESSO_REMOVIDO_INICIO: 'Processo ',
    PROCESSO_REMOVIDO_FIM: ' removido',
    TITULO_PROCESSOS_LABEL: 'Processos',
    CADASTRO_DEVOLVIDO_AJUSTES: 'O cadastro foi devolvido para ajustes!',
    ANALISE_REGISTRADA_SUCESSO: 'A análise foi registrada com sucesso!',
    CADASTRO_HOMOLOGADO_SUCESSO: 'O cadastro foi homologado com sucesso!',
} as const;

export const URLS = {
    PAINEL: '/painel',
    LOGIN: '/login',
    PROCESSO_CADASTRO: '/processo/cadastro',
    PROCESSO_DETALHE: '/processo/',
    SUBPROCESSO: '/processo/',
    VISUALIZACAO_MAPA: '/vis-mapa',
} as const;

export const ROTULOS = {
    DESCRICAO: 'Descrição',
    TIPO: 'Tipo',
    DATA_LIMITE: 'Data limite',
    NOVA_ATIVIDADE: 'Nova atividade',
    NOVO_CONHECIMENTO: 'Novo conhecimento',
    EDITAR_ATIVIDADE: 'Editar atividade',
    SUGESTOES: 'sugestões',
    OBSERVACOES: 'observações',
    OBSERVACAO: 'observação',
    TITULO_ELEITORAL: 'Título eleitoral',
    SENHA: 'Senha',
    PERFIL_UNIDADE: 'Perfil - Unidade',
} as const;

export const DADOS_TESTE = {
    PROCESSOS: {
        MAPEAMENTO_STIC: {id: 1, unidade: 'STIC'},
        REVISAO_STIC: {id: 2, unidade: 'STIC'},
        TESTE_FINALIZACAO: {id: 99, nome: 'Processo teste para finalização'},
        TESTE_MAPEAMENTO: {id: 101, nome: 'Processo teste mapeamento para finalização'},
        TESTE_REVISAO: {id: 102, nome: 'Processo teste revisão para finalização'},

    },
    UNIDADES: {
        STIC: 'STIC',
        SESEL: 'SESEL',
        SEDIA: 'SEDIA',
        SEMARE: 'SEMARE',
        SEDOC: 'SEDOC',
    },
    PERFIS: {
        ADMIN: {idServidor: '6', perfil: 'ADMIN', unidade: 'SEDOC'},
        GESTOR: {idServidor: '1', perfil: 'GESTOR', unidade: 'SESEL'},
        CHEFE: {idServidor: '14', perfil: 'CHEFE', unidade: 'STIC'},
        CHEFE_SEDIA: {idServidor: '14', perfil: 'CHEFE', unidade: 'SEDIA'},
        SERVIDOR: {idServidor: '15', perfil: 'SERVIDOR', unidade: 'STIC'},
    },
} as const;

export const SELETORES_CSS = {
    MODAL_VISIVEL: '.modal.show',
    NOTIFICACAO_SUCESSO: '.notification-success',
    NOTIFICACAO_EMAIL: '.notification-email',
    NOTIFICACAO_ERRO: '.notification-error',
    CARD_ATIVIDADE: '.atividade-card',
    GRUPO_CONHECIMENTO: '.group-conhecimento',
    LINHA_TABELA: 'table tbody tr',
    CHECKBOX: 'input[type="checkbox"]',
    CHECKBOX_MARCADO: 'input[type="checkbox"]:checked',
    TITULO_CADASTRO_PROCESSO: 'h2:has-text("Cadastro de processo")',
    TITULO_MODAL_INICIAR_PROCESSO: 'h5:has-text("Iniciar processo")',
    CAMPO_DESCRICAO: '#descricao',
    CAMPO_TIPO: '#tipo',
    CAMPO_DATA_LIMITE: '#dataLimite',
    CHECKBOX_STIC: '#chk-STIC',
} as const;