create schema if not exists sgc;

create table if not exists sgc.usuario
(
    titulo_eleitoral varchar(255) not null,
    unidade_codigo   bigint,
    ramal            varchar(20),
    email            varchar(255),
    nome             varchar(255),
    primary key (titulo_eleitoral)
);

create table if not exists sgc.usuario_perfil
(
    id                       bigint generated by default as identity,
    usuario_titulo_eleitoral varchar(255) not null,
    unidade_codigo           bigint,
    perfil                   varchar(255) check (perfil in ('ADMIN', 'GESTOR', 'CHEFE', 'SERVIDOR')),
    primary key (id)
);

create table if not exists sgc.unidade
(
    codigo                   bigint generated by default as identity,
    titular_titulo           varchar(255),
    unidade_superior_codigo  bigint,
    mapa_vigente_codigo      bigint,
    data_vigencia_mapa_atual timestamp(6),
    sigla                    varchar(20),
    situacao                 varchar(20) check (situacao in ('ATIVA', 'INATIVA')),
    tipo                     varchar(20) check (tipo in
                                                ('OPERACIONAL', 'INTERMEDIARIA', 'INTEROPERACIONAL')),
    nome                     varchar(255),
    primary key (codigo)
);

create table if not exists sgc.processo
(
    codigo           bigint generated by default as identity,
    data_criacao     timestamp(6),
    data_finalizacao timestamp(6),
    data_limite      timestamp(6),
    situacao         varchar(20) check (situacao in ('CRIADO', 'EM_ANDAMENTO', 'FINALIZADO')),
    tipo             varchar(20) check (tipo in ('MAPEAMENTO', 'REVISAO', 'DIAGNOSTICO')),
    descricao        varchar(255),
    primary key (codigo)
);

create table if not exists sgc.mapa
(
    sugestoes_apresentadas       boolean,
    codigo                       bigint generated by default as identity,
    data_hora_disponibilizado    timestamp(6),
    data_hora_homologado         timestamp(6),
    unidade_codigo               bigint,
    observacoes_disponibilizacao varchar(1000),
    sugestoes                    TEXT,
    primary key (codigo)
);

create table if not exists sgc.subprocesso
(
    codigo             bigint generated by default as identity,
    data_limite_etapa1 timestamp(6),
    data_limite_etapa2 timestamp(6),
    data_fim_etapa1    timestamp(6),
    data_fim_etapa2    timestamp(6),
    mapa_codigo        bigint,
    processo_codigo    bigint,
    unidade_codigo     bigint,
    situacao_id        varchar(50) check (situacao_id in
                                          ('NAO_INICIADO',
                                           'MAPEAMENTO_CADASTRO_EM_ANDAMENTO', 'MAPEAMENTO_CADASTRO_DISPONIBILIZADO', 'MAPEAMENTO_CADASTRO_HOMOLOGADO',
                                           'MAPEAMENTO_MAPA_CRIADO', 'MAPEAMENTO_MAPA_DISPONIBILIZADO', 'MAPEAMENTO_MAPA_COM_SUGESTOES',
                                           'MAPEAMENTO_MAPA_VALIDADO', 'MAPEAMENTO_MAPA_HOMOLOGADO',
                                           'REVISAO_CADASTRO_EM_ANDAMENTO', 'REVISAO_CADASTRO_DISPONIBILIZADA', 'REVISAO_CADASTRO_HOMOLOGADA',
                                           'REVISAO_MAPA_AJUSTADO', 'REVISAO_MAPA_DISPONIBILIZADO', 'REVISAO_MAPA_COM_SUGESTOES',
                                           'REVISAO_MAPA_VALIDADO', 'REVISAO_MAPA_HOMOLOGADO')),
    primary key (codigo)
);

create table if not exists sgc.alerta
(
    codigo                 bigint generated by default as identity,
    data_hora              timestamp(6),
    processo_codigo        bigint,
    unidade_destino_codigo bigint,
    unidade_origem_codigo  bigint,
    usuario_destino_titulo varchar(255),
    descricao              varchar(255),
    primary key (codigo)
);

create table if not exists sgc.alerta_usuario
(
    alerta_codigo            bigint not null,
    data_hora_leitura        timestamp(6),
    usuario_titulo_eleitoral varchar(255) not null,
    primary key (alerta_codigo, usuario_titulo_eleitoral)
);

create table if not exists sgc.analise
(
    codigo                  bigint generated by default as identity,
    data_hora               timestamp(6),
    subprocesso_codigo      bigint,
    acao                    varchar(20) check (acao in ('ACEITE_MAPEAMENTO', 'DEVOLUCAO_MAPEAMENTO', 'ACEITE_REVISAO',
                                                        'DEVOLUCAO_REVISAO')),
    tipo                    varchar(20) check (tipo in ('CADASTRO', 'VALIDACAO')),
    unidade_sigla           varchar(30),
    analista_usuario_titulo varchar(50),
    motivo                  varchar(500),
    observacoes             varchar(500),
    primary key (codigo)
);

create table if not exists sgc.atividade
(
    codigo      bigint generated by default as identity,
    mapa_codigo bigint,
    descricao   varchar(255),
    primary key (codigo)
);

create table if not exists sgc.atribuicao_temporaria
(
    codigo         bigint generated by default as identity,
    data_inicio    timestamp(6),
    data_termino   timestamp(6),
    unidade_codigo bigint,
    usuario_titulo varchar(255),
    justificativa  varchar(500),
    perfil         varchar(255) check (perfil in ('ADMIN', 'GESTOR', 'CHEFE', 'SERVIDOR')),
    primary key (codigo)
);

create table if not exists sgc.competencia
(
    codigo      bigint generated by default as identity,
    mapa_codigo bigint,
    descricao   varchar(255),
    primary key (codigo)
);

create table if not exists sgc.competencia_atividade
(
    atividade_codigo   bigint not null,
    competencia_codigo bigint not null,
    primary key (atividade_codigo, competencia_codigo)
);

create table if not exists sgc.conhecimento
(
    atividade_codigo bigint,
    codigo           bigint generated by default as identity,
    descricao        varchar(255),
    primary key (codigo)
);

create table if not exists sgc.movimentacao
(
    codigo                 bigint generated by default as identity,
    data_hora              timestamp(6),
    subprocesso_codigo     bigint,
    unidade_destino_codigo bigint,
    unidade_origem_codigo  bigint,
    usuario_codigo         varchar(255),
    descricao              varchar(255),
    primary key (codigo)
);

create table if not exists sgc.notificacao
(
    codigo                 bigint generated by default as identity,
    data_hora              timestamp(6),
    subprocesso_codigo     bigint,
    unidade_destino_codigo bigint,
    unidade_origem_codigo  bigint,
    conteudo               varchar(500),
    primary key (codigo)
);

create table if not exists sgc.parametro
(
    codigo    bigint generated by default as identity,
    chave     varchar(50),
    descricao varchar(255),
    valor     varchar(255),
    primary key (codigo)
);

create table if not exists sgc.unidade_processo
(
    codigo                  bigint generated by default as identity,
    processo_codigo         bigint,
    unidade_codigo          bigint,
    unidade_superior_codigo bigint,
    titular_titulo          varchar(255),
    sigla                   varchar(20),
    situacao                varchar(20),
    tipo                    varchar(20) check (tipo in
                                               ('OPERACIONAL', 'INTERMEDIARIA', 'INTEROPERACIONAL')),
    nome                    varchar(255),
    primary key (codigo)
);

create table if not exists sgc.vinculacao_unidade
(
    codigo                  bigint generated by default as identity,
    unidade_anterior_codigo bigint,
    unidade_atual_codigo    bigint,
    primary key (codigo)
);


-- Foreign Keys (H2 compatible)
alter table if exists sgc.alerta
    add constraint fk_alerta_processo foreign key (processo_codigo) references sgc.processo;
alter table if exists sgc.alerta
    add constraint fk_alerta_unidade_destino foreign key (unidade_destino_codigo) references sgc.unidade;
alter table if exists sgc.alerta
    add constraint fk_alerta_unidade_origem foreign key (unidade_origem_codigo) references sgc.unidade;
alter table if exists sgc.alerta
    add constraint fk_alerta_usuario_destino foreign key (usuario_destino_titulo) references sgc.usuario;
alter table if exists sgc.alerta_usuario
    add constraint fk_alerta_usuario_alerta foreign key (alerta_codigo) references sgc.alerta;
alter table if exists sgc.alerta_usuario
    add constraint fk_alerta_usuario_usuario foreign key (usuario_titulo_eleitoral) references sgc.usuario;
alter table if exists sgc.analise
    add constraint fk_analise_subprocesso foreign key (subprocesso_codigo) references sgc.subprocesso;
alter table if exists sgc.atividade
    add constraint fk_atividade_mapa foreign key (mapa_codigo) references sgc.mapa;
alter table if exists sgc.atribuicao_temporaria
    add constraint fk_atribuicao_temporaria_unidade foreign key (unidade_codigo) references sgc.unidade;
alter table if exists sgc.atribuicao_temporaria
    add constraint fk_atribuicao_temporaria_usuario foreign key (usuario_titulo) references sgc.usuario;
alter table if exists sgc.competencia
    add constraint fk_competencia_mapa foreign key (mapa_codigo) references sgc.mapa;
alter table if exists sgc.competencia_atividade
    add constraint fk_competencia_atividade_atividade foreign key (atividade_codigo) references sgc.atividade;
alter table if exists sgc.competencia_atividade
    add constraint fk_competencia_atividade_competencia foreign key (competencia_codigo) references sgc.competencia;
alter table if exists sgc.conhecimento
    add constraint fk_conhecimento_atividade foreign key (atividade_codigo) references sgc.atividade;
alter table if exists sgc.mapa
    add constraint fk_mapa_unidade foreign key (unidade_codigo) references sgc.unidade;
alter table if exists sgc.movimentacao
    add constraint fk_movimentacao_subprocesso foreign key (subprocesso_codigo) references sgc.subprocesso;
alter table if exists sgc.movimentacao
    add constraint fk_movimentacao_unidade_destino foreign key (unidade_destino_codigo) references sgc.unidade;
alter table if exists sgc.movimentacao
    add constraint fk_movimentacao_unidade_origem foreign key (unidade_origem_codigo) references sgc.unidade;
alter table if exists sgc.movimentacao
    add constraint fk_movimentacao_usuario foreign key (usuario_codigo) references sgc.usuario;
alter table if exists sgc.notificacao
    add constraint fk_notificacao_subprocesso foreign key (subprocesso_codigo) references sgc.subprocesso;
alter table if exists sgc.notificacao
    add constraint fk_notificacao_unidade_destino foreign key (unidade_destino_codigo) references sgc.unidade;
alter table if exists sgc.notificacao
    add constraint fk_notificacao_unidade_origem foreign key (unidade_origem_codigo) references sgc.unidade;
alter table if exists sgc.subprocesso
    add constraint fk_subprocesso_mapa foreign key (mapa_codigo) references sgc.mapa;
alter table if exists sgc.subprocesso
    add constraint fk_subprocesso_processo foreign key (processo_codigo) references sgc.processo;
alter table if exists sgc.subprocesso
    add constraint fk_subprocesso_unidade foreign key (unidade_codigo) references sgc.unidade;
alter table if exists sgc.unidade
    add constraint fk_unidade_titular foreign key (titular_titulo) references sgc.usuario;
alter table if exists sgc.unidade
    add constraint fk_unidade_mapa_vigente foreign key (mapa_vigente_codigo) references sgc.mapa;
alter table if exists sgc.unidade
    add constraint fk_unidade_superior foreign key (unidade_superior_codigo) references sgc.unidade;
alter table if exists sgc.usuario
    add constraint fk_usuario_unidade foreign key (unidade_codigo) references sgc.unidade;
alter table if exists sgc.usuario_perfil
    add constraint fk_usuario_perfil_usuario foreign key (usuario_titulo_eleitoral) references sgc.usuario;
alter table if exists sgc.usuario_perfil
    add constraint fk_usuario_perfil_unidade foreign key (unidade_codigo) references sgc.unidade;
alter table if exists sgc.vinculacao_unidade
    add constraint fk_vinculacao_unidade_anterior foreign key (unidade_anterior_codigo) references sgc.unidade;
alter table if exists sgc.vinculacao_unidade
    add constraint fk_vinculacao_unidade_atual foreign key (unidade_atual_codigo) references sgc.unidade;
