= CDU-10 - Disponibilizar revisão do cadastro de atividades e conhecimentos

Ator: CHEFE

Pré-condições:

* Usuário logado com perfil CHEFE.
* Subprocesso de revisão da unidade na situação 'Revisão do cadastro em andamento'.

Fluxo principal:

. No Painel, CHEFE clica no processo de revisão na situação 'Em andamento'.

. O sistema mostra tela Detalhes do subprocesso da unidade.

. CHEFE clica em Atividades e conhecimentos.

. O sistema mostra a tela Cadastro de atividades e conhecimentos preenchida com os dados cadastrados/revisados até o
momento.

. Se o subprocesso tiver retornado de análise pelas unidades superiores, deverá ser exibido, além dos botões fixos da
tela, o botão Histórico de análise.

.. Se CHEFE clicar no botão `Histórico de análise`, o sistema mostra, em tela modal, os dados das análises do
cadastro realizadas pelas unidades superiores desde a última disponibilização.
*** As análises deverão ser apresentadas em uma pequena tabela com data/hora, sigla da unidade, resultado ('Devolução'
ou 'Aceite') e observações. Essas informações poderão ser usadas como subsídio para ajustes no cadastro, antes da
realização de nova disponibilização.

. CHEFE clica no botão `Disponibilizar`.

. O sistema verifica se todas as atividades têm ao menos um conhecimento associado.

.. Caso negativo, indica quais atividades estão precisando de adição de conhecimentos e interrompe a operação de
disponibilização, permanecendo na mesma tela.

. O sistema mostra diálogo de confirmação: título "Disponibilização da revisão do cadastro", mensagem "Confirma a
finalização da revisão e a disponibilização do cadastro? Essa ação bloqueia a edição e habilita a análise do cadastro
por unidades superiores" / Botões `Confirmar` e `Cancelar`.

.. Caso CHEFE escolha `Cancelar`, o sistema interrompe a operação de disponibilização, permanecendo na mesma tela.

. CHEFE escolhe `Confirmar`.

. O sistema altera a situação do subprocesso da unidade para 'Revisão do cadastro disponibilizada'

. O sistema registra uma movimentação para o subprocesso com os campos:

*** Data/hora: Data/hora atual
*** Unidade origem: [SIGLA_UNIDADE_SUBPROCESSO]
*** Unidade destino: [SIGLA_UNIDADE_SUPERIOR]
*** Descrição: 'Disponibilização da revisão do cadastro de atividades'

. O sistema notifica unidade superior hierárquica quanto à disponibilização, com e-mail no modelo abaixo:

Assunto: SGC: Revisão do cadastro de atividades e conhecimentos disponibilizada: [SIGLA_UNIDADE_SUBPROCESSO]

[source,text]
----

Prezado(a) responsável pela [SIGLA_UNIDADE_SUPERIOR],

A unidade [SIGLA_UNIDADE_SUBPROCESSO] concluiu a revisão e disponibilizou seu cadastro de atividades e conhecimentos do processo [DESCRICAO_PROCESSO].

A análise desse cadastro já pode ser realizada no O sistema de Gestão de Competências ([URL_SISTEMA]).
----

. O sistema cria internamente um alerta com:

*** Descrição: "Cadastro de atividades e conhecimentos da unidade [SIGLA_UNIDADE_SUBPROCESSO] disponibilizado para
análise"
*** Processo: [DESCRICAO_PROCESSO]
*** Data/hora: [Data/hora atual]
*** Unidade de origem: [SIGLA_UNIDADE_SUBPROCESSO]
*** Unidade de destino: [SIGLA_UNIDADE_SUPERIOR].

. O sistema define a data/hora de conclusão da etapa 1 do subprocesso da unidade como sendo a data/hora atual.

. O sistema exclui o histórico de análise do cadastro do subprocesso da unidade.

. O sistema redireciona para o Painel, e mostra a mensagem "Revisão do cadastro de atividades disponibilizada".
