= CDU-20 - Analisar validação de mapa de competências

Ator: GESTOR e ADMIN

== Pré-condições

* Usuário logado com perfil GESTOR ou ADMIN.
* Processo de mapeamento ou de revisão iniciado que tenha a unidade como participante.
* Subprocesso nas situações 'Mapa validado' ou 'Mapa com sugestões' e com localização atual na unidade do usuário.

== Fluxo principal

. No Painel, usuário escolhe um processo e na tela Detalhes do processo clica em uma unidade com situação 'Mapa validado' ou 'Mapa com sugestões'.

. O sistema mostra a tela `Detalhes do subprocesso`.

. Usuário clica no card `Mapa de Competências`.

. O sistema apresenta o mapa de competências da unidade na tela `Visualização de mapa`, com os botões:

*** `Histórico de análise`;
*** `Devolver para ajustes`;
*** `Registrar aceite`, caso o perfil seja GESTOR ou `Homologar`, caso o perfil seja ADMIN.

. Caso a situação do subprocesso seja 'Mapa com sugestões', a tela Visualização de mapa incluirá ainda, antes do botão `Histórico de análise`, o botão `Ver sugestões`, a partir do qual será possível visualizar, em uma tela modal, as sugestões registradas para o mapa no subprocesso da unidade.

. Se o usuário clicar no botão `Histórico de análise`, o sistema mostra, em tela modal, os dados das análises prévias registradas para a validação do mapa. As análises deverão ser apresentadas em uma pequena tabela com data/hora, sigla da unidade, resultado ('Devolução' ou 'Aceite') e observações. Essas informações poderão ser usadas como subsídio para a realização da análise pela unidade atual.

. O usuário analisa as informações e opta por aceitar/homologar ou devolver a validação para ajustes.

. Se optar por devolver para ajustes:

.. Usuário clica em `Devolver para ajustes`.

.. O sistema abre um modal (título "Devolução") com a pergunta "Confirma a devolução da validação do mapa para ajustes", um campo para preenchimento de uma observação (opcional) e os botões `Confirmar` ou `Cancelar`.

.. Caso o usuário escolha `Cancelar`, o sistema interrompe a operação de devolução, permanecendo na tela `Visualização de mapa`.

.. O usuário opcionalmente informa a observação e escolhe `Confirmar`.

.. O sistema registra uma análise de validação para o subprocesso com:

*** `Data/hora`: Data/hora atual
*** `Unidade`: [SIGLA_UNIDADE_ANALISE]
*** `Resultado`: 'Devolução'
*** `Observação`: A observação da janela modal, caso tenha sido fornecida.

.. O sistema identifica a unidade de devolução como sendo a unidade de origem da última movimentação do subprocesso.

.. O sistema registra uma movimentação para o subprocesso com:

*** `Descrição`: 'Devolução da validação do mapa de competências para ajustes'
*** `Data/hora`: Data/hora atual
*** `Unidade origem`: [SIGLA_UNIDADE_ANALISE]
*** `Unidade destino`: [SIGLA_UNIDADE_DEVOLUCAO]

.. Se a unidade de devolução for a própria unidade do subprocesso, o sistema altera a situação do subprocesso para 'Mapa disponibilizado' e apaga a data/hora de conclusão da etapa 2 do subprocesso da unidade.

.. O sistema envia notificação por e-mail para a unidade de devolução:
+
[source,text]
----

Assunto: SGC: Validação do mapa de competências da [SIGLA_UNIDADE_SUBPROCESSO] devolvida  para ajustes

Prezado(a) responsável pela [SIGLA_UNIDADE_DEVOLUCAO],

A validação do mapa de competências da [SIGLA_UNIDADE_SUBPROCESSO] no processo [DESCRICAO_PROCESSO] foi devolvida para ajustes.

Acompanhe o processo no O sistema de Gestão de Competências: [URL_SISTEMA].
----

.. O sistema cria internamente um alerta com:

*** Descrição: "Cadastro de atividades e conhecimentos da unidade [SIGLA_UNIDADE_SUBPROCESSO] devolvido para ajustes"
*** Processo: [DESCRICAO_PROCESSO]
*** Data/hora: Data/hora atual
*** Unidade de origem: [SIGLA_UNIDADE_ANALISE]
*** Unidade de destino: [SIGLA_UNIDADE_DEVOLUCAO].

.. O sistema redireciona para o Painel e mostra a mensagem "Devolução realizada".

. Se optar por aceitar (perfil GESTOR):

.. Usuário clica em `Registrar aceite`.

.. O sistema abre um diálogo modal (título "Aceite") com a pergunta "Confirma o aceite da validação do mapa de competências?", um campo para preenchimento de uma observação opcional e os botões `Confirmar` ou `Cancelar`.

.. Caso o usuário escolha o botão Cancelar, o sistema interrompe a operação de aceite, permanecendo na tela `Visualização de mapa`.

.. O usuário opcionalmente informa a observação e escolhe `Confirmar`.

.. O sistema registra uma análise de validação para o subprocesso com:

*** `Data/hora`: Data/hora atual
*** `Unidade`: [SIGLA_UNIDADE_ANALISE]
*** `Resultado`: 'Aceite'
*** `Observação`: A observação da janela modal, caso tenha sido fornecida.

.. O sistema registra uma movimentação para o subprocesso com:

*** Data/hora: Data/hora atual
*** Unidade origem: [SIGLA_UNIDADE_ANALISE]
*** Unidade destino: [SIGLA_UNIDADE_SUPERIOR]
*** Descrição: 'Mapa de competências validado'

.. O sistema envia notificação por e-mail para a unidade superior:
+
[source,text]
----

Assunto: SGC: Validação do mapa de competências da [SIGLA_UNIDADE_SUBPROCESSO] submetida para análise 

Prezado(a) responsável pela [SIGLA_UNIDADE_SUPERIOR],

A validação do mapa de competências da [SIGLA_UNIDADE_SUBPROCESSO] no processo [DESCRICAO_PROCESSO] foi submetida para análise por essa unidade. 

A análise já pode ser realizada no O sistema de Gestão de Competências ([URL_SISTEMA]).
----

.. O sistema cria internamente um alerta com:

*** Descrição: "Validação do mapa de competências da [SIGLA_UNIDADE_SUBPROCESSO] submetida para análise"
*** Processo: [DESCRICAO_PROCESSO]
*** Data/hora: Data/hora atual
*** Unidade de origem: [SIGLA_UNIDADE_ANALISE]
*** Unidade de destino: [SIGLA_UNIDADE_SUPERIOR].

.. O sistema redireciona para o Painel e mostra a mensagem "Aceite registrado".

. Se optar por homologar (perfil ADMIN):

.. Usuário escolhe `Homologar`.

.. O sistema abre um diálogo de confirmação (título 'Homologação') com a pergunta 'Confirma a homologação do mapa de competências?' e os botões `Confirmar` ou `Cancelar`.

.. Caso o usuário escolha o botão `Cancelar`, o sistema interrompe a operação de homologação, permanecendo na mesma tela.

.. Usuário escolhe `Confirmar`.

.. O sistema altera a situação do subprocesso da unidade para 'Mapa homologado'.

.. O sistema redireciona para o painel e mostra a mensagem "Homologação efetivada".
