= CDU-15 - Manter mapa de competências

Ator: ADMIN

== Pré-condições

* Processo de mapeamento com ao menos uma unidade com subprocesso nas situações 'Cadastro homologado' ou 'Mapa criado'.

== Fluxo principal

. No Painel ADMIN escolhe um processo na tela Detalhes do processo clica em uma unidade operacional ou interoperacional com subprocesso nas situações 'Cadastro homologado' ou 'Mapa criado'.

. O sistema mostra a tela Detalhes do subprocesso.

. ADMIN clica no card Mapa de Competências.

. O sistema mostra a tela Edição de mapa preenchida com os dados do mapa da unidade, com os seguintes elementos visuais:

*** Um bloco para cada competência criada, cujo título é a descrição da competência
*** Ao lado da descrição da competência, botões de ação (ícones), para editar e para excluir a competência.
*** Dentro de cada bloco de uma competência, mostrar as descrições das atividades associadas à competência em pequenos blocos internos.
*** À direita da descrição de cada atividade mostrar um badge com o número de conhecimentos da atividade. Ao passar o mouse sobre esse badge, o sistema exibirá em um tooltip a lista de conhecimentos da atividade.
*** Botões `Criar competência` e `Disponibilizar` alinhados no canto superior direito da lista de blocos de competências

. *<<Início de fluxo de criação de competências>>* ADMIN clica no botão Criar competência.

. O sistema abre a tela modal Edição de competência, com:

*** Campo para descrição da competência.
*** Lista das atividades cadastradas pela unidade, cada uma podendo ser selecionada para inclusão na competência.
*** Botões `Cancelar` e `Salvar`.

. ADMIN informa a descrição da competência que será criada e seleciona uma ou mais atividades para associar a ela e clica em Salvar para confirmar as mudanças.

. O sistema armazena internamente a competência e o vínculo desta com as atividades selecionadas

. O sistema insere a competência criada no mapa de competências.

. Se a situação do subprocesso da unidade ainda for 'Cadastro homologado', o sistema altera a situação para 'Mapa criado'. *<< Término de fluxo de criação de competências >>*

. ADMIN repete o fluxo de criação de competências até que o mapa esteja completo.

. Se desejar *editar* uma competência criada:

.. ADMIN clica no botão de ação de editar no cabeçalho do bloco correspondente à competência.

.. O sistema exibe a tela Edição de competência preenchida com a descrição da competência e apresenta selecionadas as atividades atualmente associadas à competência.

.. ADMIN altera a descrição ou a associação com as atividades e clica no botão Salvar.

.. O sistema armazena a nova descrição da competência e os vínculos com as atividades.

.. O sistema retorna para a tela Edição do mapa, exibindo o bloco da competência correspondente atualizado.

. Se desejar *excluir* uma competência criada:

.. ADMIN clica no botão de ação de excluir no cabeçalho do bloco correspondente à competência.

.. O sistema mostra diálogo de confirmação: Título "Exclusão de competência", mensagem "Confirma a exclusão da competência [DESCRICAO_COMPETENCIA]?", Botões `Confirmar` e `Cancelar`.

.. ADMIN confirma a exclusão.

.. O sistema remove a competência e todos os seus vínculos com as atividades da unidade.

.. O sistema retorna para a tela `Edição do mapa`, mostrando o bloco da competência correspondente atualizado.

. Se o usuário clicar em `Disponibilizar`, o sistema segue para o caso de uso `Disponibilizar mapa de competências`.
