= CDU-16 - Ajustar mapa de competências

Ator: ADMIN

== Pré-condições

* Processo de Revisão, com ao menos uma unidade com subprocesso nas situações 'Revisão do cadastro homologada' ou 'Mapa ajustado'.

== Fluxo principal

. No `Painel`, ADMIN escolhe o processo de revisão desejado.

. O sistema mostra tela `Detalhes do processo`.

. ADMIN clica em uma unidade operacional ou interoperacional com subprocesso nas situações 'Revisão do cadastro homologada' ou 'Mapa ajustado'.

. O sistema mostra a tela `Detalhes do subprocesso` para a unidade selecionada.

. ADMIN clica no card `Mapa de Competências`.

. O sistema mostra a tela `Edição de mapa` preenchida com o mapa do subprocesso da unidade (ver detalhes sobre a tela no caso de uso `Manter mapa de competências`, com os botões Impactos no mapa e `Disponibilizar`.

. ADMIN clica em `Impactos no mapa`.

. O sistema mostra o modal `Impactos no mapa`. Ver caso de uso `Verificar impactos no mapa de competências`.

. ADMIN usa como base as informações de impactos mostradas nesta tela para alterar o mapa, podendo alterar descrições de competências, de atividades e de conhecimentos; remover ou criar novas competências; e ajustar a associação das atividades às competências do mapa, conforme descrito no caso de uso `Manter mapa de competências`.

.. ADMIN deve associar a uma competência todas as atividades ainda não associadas.

. Quando concluir os ajustes, ADMIN clica em `Disponibilizar` e o sistema segue o fluxo descrito no caso de uso `Disponibilizar mapa de competências`.
