= CDU-13 - Analisar cadastro de atividades e conhecimentos

Atores: GESTOR e ADMIN

== Pré-condições

* Usuário logado com perfil GESTOR ou ADMIN
* Processo de mapeamento iniciado que tenha a unidade como participante
* Subprocesso com cadastro de atividades e conhecimentos já disponibilizado, e com localização atual na unidade do usuário.

Fluxo principal:

. No Painel, o usuário clica no processo de mapeamento.

. O sistema exibe a tela `Detalhes do processo`.

. Usuário clica na unidade subordinada cujo cadastro de atividades deseja validar.

. O sistema exibe a tela `Detalhes do subprocesso` com os dados da unidade selecionada.

. Usuário clica no card `Atividades e conhecimentos`.

. O sistema apresenta as atividades e conhecimentos da unidade na tela `Atividades e conhecimentos`, com os botões:

** `Histórico de análise`
** `Devolver para ajustes`
** `Registrar aceite`, caso o perfil seja GESTOR ou `Homologar`, caso o perfil seja ADMIN.

. Se o usuário clicar no botão `Histórico de análise`, o sistema mostra, em tela modal, os dados das análises prévias registradas para o cadastro de atividades desde a última disponibilização. As análises serão apresentadas em uma pequena tabela com data/hora, sigla da unidade, resultado ('Devolução' ou 'Aceite') e observações. Essas informações serão usadas como subsídio para a realização da análise pela unidade atual.

. O usuário analisa as informações e opta por aceitar/homologar ou devolver o cadastro para ajustes.

. Se optar por devolver para ajustes:

.. Usuário clica em `Devolver para ajustes`.

.. O sistema abre tela modal (título "Devolução") com a pergunta 'Confirma a devolução do cadastro para ajustes?', um campo de observação (opcional) e os botões `Confirmar` ou `Cancelar`.

.. Caso o usuário escolha `Cancelar`, o sistema interrompe a operação de devolução do cadastro, permanecendo na tela `Atividades e conhecimentos`.

.. O usuário opcionalmente informa a observação e escolhe `Confirmar`.

.. O sistema registra uma análise de cadastro para o subprocesso:

*** `Data/hora`: Data/hora atual
*** `Unidade`: [SIGLA_UNIDADE_ANALISE]
*** `Resultado`: 'Devolução'
*** `Observação`: A observação da janela modal, caso tenha sido fornecida.

.. O sistema identifica a unidade de devolução como sendo a unidade de origem da última movimentação do subprocesso.

.. O sistema registra uma movimentação para o subprocesso:

** `Data/hora`: Data/hora atual
** `Unidade origem`: [SIGLA_UNIDADE_ANALISE]
** `Descrição`: 'Devolução do cadastro de atividades e conhecimentos para ajustes'

.. Se a unidade de devolução for a própria unidade do subprocesso, o sistema altera a situação do subprocesso para 'Cadastro em andamento' e apaga a data/hora de conclusão da etapa 1 do subprocesso da unidade.

.. O sistema envia notificação por e-mail para a unidade de devolução:
+
[source,text]
----

Assunto: SGC: Cadastro de atividades e conhecimentos da [SIGLA_UNIDADE_SUBPROCESSO] devolvido para ajustes

Prezado(a) responsável pela [SIGLA_UNIDADE_DEVOLUCAO],

O cadastro de atividades e conhecimentos da [SIGLA_UNIDADE_SUBPROCESSO] no processo [DESCRIÇÃO_PROCESSO] foi
devolvido para ajustes.

Acompanhe o processo no sistema de Gestão de Competências: [URL_SISTEMA].
----

.. O sistema cria internamente um alerta:

*** `Descrição`: "Cadastro de atividades e conhecimentos da unidade [SIGLA_UNIDADE_SUBPROCESSO] devolvido para ajustes"
*** `Processo`: [DESCRICAO_PROCESSO]
*** `Data/hora`: Data/hora atual
*** `Unidade de origem`: [SIGLA_UNIDADE_ANALISE]
*** `Unidade de destino`: [SIGLA_UNIDADE_DEVOLUCAO].

.. O sistema redireciona para o Painel, e mostra a mensagem "Devolução realizada".

. Se optar por aceitar (perfil GESTOR):

.. Usuário clica em `Registrar aceite`.

.. O sistema abre um diálogo modal (título "Aceite") com a pergunta "Confirma o aceite do cadastro de atividades?", um campo para preenchimento de uma observação opcional e os botões Confirmar ou Cancelar.

.. Caso o usuário escolha o botão `Cancelar`, o sistema interrompe a operação de aceite, permanecendo na mesma tela.

.. O usuário opcionalmente informa a observação e escolhe `Confirmar`.

.. O sistema registra uma análise de cadastro para o subprocesso:

* `Data/hora`: Data/hora atual
* `Unidade`: [SIGLA_UNIDADE_ANALISE]
* `Resultado`: 'Aceite'
* `Observação`: A observação da janela modal, caso tenha sido fornecida.

.. O sistema registra uma movimentação para o subprocesso:

* `Data/hora`: Data/hora atual
* `Unidade origem`: [SIGLA_UNIDADE_ANALISE]
* `Unidade destino`: [SIGLA_UNIDADE_SUPERIOR]
* `Descrição`: 'Cadastro de atividades e conhecimentos aceito'

.. O sistema envia notificação por e-mail para a unidade superior:
+
[source,text]
----

Assunto: SGC: Cadastro de atividades e conhecimentos da [SIGLA_UNIDADE_SUBPROCESSO] submetido para análise

Prezado(a) responsável pela [SIGLA_UNIDADE_SUPERIOR],

O cadastro de atividades e conhecimentos da [SIGLA_UNIDADE_SUBPROCESSO] no processo [DESCRICAO_PROCESSO] foi submetido para análise por essa unidade.

A análise já pode ser realizada no sistema de Gestão de Competências ([URL_SISTEMA]).
----

.. O sistema cria internamente um alerta:

* `Descrição`: "Cadastro de atividades e conhecimentos da unidade [SIGLA_UNIDADE_SUBPROCESSO] submetido para análise"
* `Processo`: [DESCRICA_PROCESSO]
* `Data/hora`: Data/hora atual
* `Unidade de origem`: [SIGLA_UNIDADE_ANALISE]
* `Unidade de destino`: [SIGLA_UNIDADE_SUPERIOR].

.. O sistema mostra a mensagem "Aceite registrado" e redireciona para o Painel.

. Se optar por *homologar* (perfil ADMIN):

.. Usuário escolhe `Homologar`.

.. O sistema abre um modal de confirmação (título "Homologação do cadastro de atividades e conhecimentos") com a pergunta "Confirma a homologação do cadastro de atividades e conhecimentos?" e os botões `Confirmar` ou `Cancelar`.

.. Caso o usuário escolha o botão `Cancelar`, o sistema interrompe a operação de homologação do cadastro, permanecendona mesma tela.

.. Usuário escolhe `Confirmar`.

.. O sistema registra uma movimentação para o subprocesso:

** `Data/hora`: Data/hora atual
** `Unidade origem`: 'SEDOC'
** `Unidade destino`: 'SEDOC'
** `Descrição`: 'Cadastro de atividades e conhecimentos homologado'

.. O sistema altera a situação do subprocesso da unidade para 'Cadastro homologado'.

.. O sistema redireciona para a tela `Detalhes do subprocesso` e mostra a mensagem "Homologação efetivada".
