create schema if not exists sgc;

-- Tabelas físicas que eram VIEWs no Oracle, mas no H2 de testes são tabelas simples
create table if not exists sgc.vw_usuario
(
    titulo               varchar(12) not null,
    matricula            varchar(8),
    nome                 varchar(255),
    email                varchar(255),
    ramal                varchar(20),
    unidade_lot_codigo   bigint,
    unidade_comp_codigo  bigint,
    primary key (titulo)
);

create table if not exists sgc.administrador
(
    usuario_titulo varchar(12) not null,
    primary key (usuario_titulo)
);

create table if not exists sgc.vw_unidade
(
    codigo                   bigint generated by default as identity,
    nome                     varchar(255),
    sigla                    varchar(20),
    matricula_titular        varchar(8),
    titulo_titular           varchar(12),
    data_inicio_titularidade timestamp(6),
    tipo                     varchar(20) check (tipo in ('OPERACIONAL', 'INTERMEDIARIA', 'INTEROPERACIONAL', 'SEM_EQUIPE', 'RAIZ')),
    situacao                 varchar(20) check (situacao in ('ATIVA', 'INATIVA')),
    unidade_superior_codigo  bigint,
    primary key (codigo)
);

create table if not exists sgc.unidade_mapa
(
    unidade_codigo      bigint not null,
    mapa_vigente_codigo bigint not null,
    primary key (unidade_codigo)
);

create table if not exists sgc.vw_usuario_perfil_unidade
(
    usuario_titulo varchar(12) not null,
    unidade_codigo bigint not null,
    perfil         varchar(255) check (perfil in ('ADMIN', 'GESTOR', 'CHEFE', 'SERVIDOR')),
    primary key (usuario_titulo, unidade_codigo, perfil)
);

create table if not exists sgc.vw_vinculacao_unidade
(
    unidade_atual_codigo    bigint not null,
    unidade_anterior_codigo bigint not null,
    demais_unidades_historicas varchar(1000),
    primary key (unidade_atual_codigo, unidade_anterior_codigo)
);

create table if not exists sgc.processo
(
    codigo           bigint generated by default as identity,
    data_criacao     timestamp(6),
    data_finalizacao timestamp(6),
    data_limite      timestamp(6),
    situacao         varchar(20) check (situacao in ('CRIADO', 'EM_ANDAMENTO', 'FINALIZADO')),
    tipo             varchar(20) check (tipo in ('MAPEAMENTO', 'REVISAO', 'DIAGNOSTICO')),
    descricao        varchar(255),
    primary key (codigo)
);

create table if not exists sgc.mapa
(
    codigo                       bigint generated by default as identity,
    subprocesso_codigo           bigint,
    data_hora_disponibilizado    timestamp(6),
    data_hora_homologado         timestamp(6),
    observacoes_disponibilizacao varchar(1000),
    sugestoes                    varchar(1000),
    primary key (codigo)
);

create table if not exists sgc.subprocesso
(
    codigo             bigint generated by default as identity,
    data_limite_etapa1 timestamp(6),
    data_limite_etapa2 timestamp(6),
    data_fim_etapa1    timestamp(6),
    data_fim_etapa2    timestamp(6),
    processo_codigo    bigint,
    unidade_codigo     bigint,
    situacao           varchar(50) check (situacao in
                                          ('NAO_INICIADO',
                                           'MAPEAMENTO_CADASTRO_EM_ANDAMENTO', 'MAPEAMENTO_CADASTRO_DISPONIBILIZADO',
                                           'MAPEAMENTO_CADASTRO_HOMOLOGADO',
                                           'MAPEAMENTO_MAPA_CRIADO', 'MAPEAMENTO_MAPA_DISPONIBILIZADO',
                                           'MAPEAMENTO_MAPA_COM_SUGESTOES',
                                           'MAPEAMENTO_MAPA_VALIDADO', 'MAPEAMENTO_MAPA_HOMOLOGADO',
                                           'REVISAO_CADASTRO_EM_ANDAMENTO', 'REVISAO_CADASTRO_DISPONIBILIZADA',
                                           'REVISAO_CADASTRO_HOMOLOGADA',
                                           'REVISAO_MAPA_AJUSTADO', 'REVISAO_MAPA_DISPONIBILIZADO',
                                           'REVISAO_MAPA_COM_SUGESTOES',
                                           'REVISAO_MAPA_VALIDADO', 'REVISAO_MAPA_HOMOLOGADO',
                                           'DIAGNOSTICO_AUTOAVALIACAO_EM_ANDAMENTO', 'DIAGNOSTICO_MONITORAMENTO',
                                           'DIAGNOSTICO_CONCLUIDO')),
    primary key (codigo)
);

create table if not exists sgc.alerta
(
    codigo                 bigint generated by default as identity,
    data_hora              timestamp(6),
    processo_codigo        bigint,
    unidade_destino_codigo bigint,
    unidade_origem_codigo  bigint,
    usuario_destino_titulo varchar(12),
    descricao              varchar(255),
    primary key (codigo)
);

create table if not exists sgc.alerta_usuario
(
    alerta_codigo     bigint      not null,
    data_hora_leitura timestamp(6),
    usuario_titulo    varchar(12) not null,
    primary key (alerta_codigo, usuario_titulo)
);

create table if not exists sgc.analise
(
    codigo                  bigint generated by default as identity,
    data_hora               timestamp(6),
    subprocesso_codigo      bigint,
    acao                    varchar(20) check (acao in ('ACEITE_MAPEAMENTO', 'DEVOLUCAO_MAPEAMENTO', 'ACEITE_REVISAO',
                                                        'DEVOLUCAO_REVISAO')),
    tipo                    varchar(20) check (tipo in ('CADASTRO', 'VALIDACAO')),
    unidade_codigo          bigint,
    usuario_titulo          varchar(12),
    motivo                  varchar(500),
    observacoes             varchar(500),
    primary key (codigo)
);

create table if not exists sgc.atividade
(
    codigo      bigint generated by default as identity,
    mapa_codigo bigint,
    descricao   varchar(255),
    primary key (codigo)
);

create table if not exists sgc.atribuicao_temporaria
(
    codigo            bigint generated by default as identity,
    data_inicio       timestamp(6),
    data_termino      timestamp(6),
    unidade_codigo    bigint,
    usuario_titulo    varchar(12),
    usuario_matricula varchar(8),
    justificativa     varchar(500),
    primary key (codigo)
);

create table if not exists sgc.competencia
(
    codigo      bigint generated by default as identity,
    mapa_codigo bigint,
    descricao   varchar(255),
    primary key (codigo)
);

create table if not exists sgc.competencia_atividade
(
    atividade_codigo   bigint not null,
    competencia_codigo bigint not null,
    primary key (atividade_codigo, competencia_codigo)
);

create table if not exists sgc.conhecimento
(
    atividade_codigo bigint,
    codigo           bigint generated by default as identity,
    descricao        varchar(255),
    primary key (codigo)
);

create table if not exists sgc.movimentacao
(
    codigo                 bigint generated by default as identity,
    data_hora              timestamp(6),
    subprocesso_codigo     bigint,
    unidade_destino_codigo bigint,
    unidade_origem_codigo  bigint,
    usuario_codigo         varchar(12),
    descricao              varchar(255),
    primary key (codigo)
);

create table if not exists sgc.notificacao
(
    codigo                 bigint generated by default as identity,
    data_hora              timestamp(6),
    subprocesso_codigo     bigint,
    unidade_destino_codigo bigint,
    unidade_origem_codigo  bigint,
    conteudo               varchar(500),
    primary key (codigo)
);

create table if not exists sgc.parametro
(
    codigo    bigint generated by default as identity,
    chave     varchar(50),
    descricao varchar(255),
    valor     varchar(255),
    primary key (codigo)
);

create table if not exists sgc.unidade_processo
(
    processo_codigo          bigint not null,
    unidade_codigo           bigint not null,
    nome                     varchar(255),
    sigla                    varchar(20),
    matricula_titular        varchar(8),
    titulo_titular           varchar(12),
    data_inicio_titularidade timestamp(6),
    tipo                     varchar(20) check (tipo in ('OPERACIONAL', 'INTERMEDIARIA', 'INTEROPERACIONAL')),
    situacao                 varchar(20),
    unidade_superior_codigo  bigint,
    primary key (processo_codigo, unidade_codigo)
);


-- Foreign Keys (H2 compatible)
alter table if exists sgc.alerta
    add constraint fk_alerta_processo foreign key (processo_codigo) references sgc.processo;
alter table if exists sgc.alerta
    add constraint fk_alerta_usuario_destino foreign key (usuario_destino_titulo) references sgc.vw_usuario;
alter table if exists sgc.alerta_usuario
    add constraint fk_alerta_usuario_alerta foreign key (alerta_codigo) references sgc.alerta;
alter table if exists sgc.alerta_usuario
    add constraint fk_alerta_usuario_usuario foreign key (usuario_titulo) references sgc.vw_usuario;
alter table if exists sgc.analise
    add constraint fk_analise_subprocesso foreign key (subprocesso_codigo) references sgc.subprocesso;
alter table if exists sgc.atividade
    add constraint fk_atividade_mapa foreign key (mapa_codigo) references sgc.mapa;
alter table if exists sgc.atribuicao_temporaria
    add constraint fk_atribuicao_temporaria_unidade foreign key (unidade_codigo) references sgc.vw_unidade;
alter table if exists sgc.atribuicao_temporaria
    add constraint fk_atribuicao_temporaria_usuario foreign key (usuario_titulo) references sgc.vw_usuario;
alter table if exists sgc.competencia
    add constraint fk_competencia_mapa foreign key (mapa_codigo) references sgc.mapa;
alter table if exists sgc.competencia_atividade
    add constraint fk_competencia_atividade_atividade foreign key (atividade_codigo) references sgc.atividade;
alter table if exists sgc.competencia_atividade
    add constraint fk_competencia_atividade_competencia foreign key (competencia_codigo) references sgc.competencia;
alter table if exists sgc.conhecimento
    add constraint fk_conhecimento_atividade foreign key (atividade_codigo) references sgc.atividade;
alter table if exists sgc.mapa
    add constraint fk_mapa_subprocesso foreign key (subprocesso_codigo) references sgc.subprocesso;
alter table if exists sgc.movimentacao
    add constraint fk_movimentacao_subprocesso foreign key (subprocesso_codigo) references sgc.subprocesso;
alter table if exists sgc.movimentacao
    add constraint fk_movimentacao_unidade_destino foreign key (unidade_destino_codigo) references sgc.vw_unidade;
alter table if exists sgc.movimentacao
    add constraint fk_movimentacao_unidade_origem foreign key (unidade_origem_codigo) references sgc.vw_unidade;
alter table if exists sgc.movimentacao
    add constraint fk_movimentacao_usuario foreign key (usuario_codigo) references sgc.vw_usuario;
alter table if exists sgc.notificacao
    add constraint fk_notificacao_subprocesso foreign key (subprocesso_codigo) references sgc.subprocesso;
alter table if exists sgc.notificacao
    add constraint fk_notificacao_unidade_destino foreign key (unidade_destino_codigo) references sgc.vw_unidade;
alter table if exists sgc.notificacao
    add constraint fk_notificacao_unidade_origem foreign key (unidade_origem_codigo) references sgc.vw_unidade;
alter table if exists sgc.subprocesso
    add constraint fk_subprocesso_processo foreign key (processo_codigo) references sgc.processo;
alter table if exists sgc.subprocesso
    add constraint fk_subprocesso_unidade foreign key (unidade_codigo) references sgc.vw_unidade;
alter table if exists sgc.unidade_processo
    add constraint fk_up_processo foreign key (processo_codigo) references sgc.processo;
-- FKs entre VIEWs externas removidas para evitar dependência circular nos dados de teste
-- alter table if exists sgc.vw_unidade
--     add constraint fk_unidade_titular foreign key (titulo_titular) references sgc.vw_usuario;
alter table if exists sgc.vw_unidade
    add constraint fk_unidade_superior foreign key (unidade_superior_codigo) references sgc.vw_unidade;
-- alter table if exists sgc.vw_usuario
--     add constraint fk_usuario_unidade_lot foreign key (unidade_lot_codigo) references sgc.vw_unidade;
alter table if exists sgc.vw_usuario_perfil_unidade
    add constraint fk_usuario_perfil_usuario foreign key (usuario_titulo) references sgc.vw_usuario;
alter table if exists sgc.vw_usuario_perfil_unidade
    add constraint fk_usuario_perfil_unidade foreign key (unidade_codigo) references sgc.vw_unidade;
alter table if exists sgc.vw_vinculacao_unidade
    add constraint fk_vinculacao_unidade_anterior foreign key (unidade_anterior_codigo) references sgc.vw_unidade;
alter table if exists sgc.vw_vinculacao_unidade
    add constraint fk_vinculacao_unidade_atual foreign key (unidade_atual_codigo) references sgc.vw_unidade;

-- Tabelas do Módulo de Diagnóstico
create table if not exists sgc.diagnostico
(
    codigo                  bigint generated by default as identity,
    subprocesso_codigo      bigint      not null unique,
    situacao                varchar(50) not null check (situacao in ('EM_ANDAMENTO', 'CONCLUIDO', 'VALIDADO', 'HOMOLOGADO')),
    data_conclusao          timestamp(6),
    justificativa_conclusao text,
    primary key (codigo)
);

create table if not exists sgc.avaliacao_servidor
(
    codigo             bigint generated by default as identity,
    diagnostico_codigo bigint       not null,
    servidor_titulo    varchar(255) not null,
    competencia_codigo bigint       not null,
    importancia        varchar(10) check (importancia in ('NA', 'N1', 'N2', 'N3', 'N4', 'N5', 'N6')),
    dominio            varchar(10) check (dominio in ('NA', 'N1', 'N2', 'N3', 'N4', 'N5', 'N6')),
    gap                int,
    observacoes        text,
    situacao_servidor  varchar(50)  not null check (situacao_servidor in (
                                                                          'AUTOAVALIACAO_NAO_REALIZADA',
                                                                          'AUTOAVALIACAO_CONCLUIDA',
                                                                          'CONSENSO_CRIADO',
                                                                          'CONSENSO_APROVADO',
                                                                          'AVALIACAO_IMPOSSIBILITADA'
        )),
    primary key (codigo),
    unique (diagnostico_codigo, servidor_titulo, competencia_codigo)
);

create table if not exists sgc.ocupacao_critica
(
    codigo               bigint generated by default as identity,
    diagnostico_codigo   bigint       not null,
    servidor_titulo      varchar(255) not null,
    competencia_codigo   bigint       not null,
    situacao_capacitacao varchar(10)  not null check (situacao_capacitacao in ('NA', 'AC', 'EC', 'C', 'I')),
    primary key (codigo),
    unique (diagnostico_codigo, servidor_titulo, competencia_codigo)
);

-- Foreign keys para Diagnóstico
alter table if exists sgc.diagnostico
    add constraint fk_diagnostico_subprocesso foreign key (subprocesso_codigo) references sgc.subprocesso;

alter table if exists sgc.avaliacao_servidor
    add constraint fk_avaliacao_diagnostico foreign key (diagnostico_codigo) references sgc.diagnostico;

alter table if exists sgc.avaliacao_servidor
    add constraint fk_avaliacao_servidor foreign key (servidor_titulo) references sgc.vw_usuario;

alter table if exists sgc.avaliacao_servidor
    add constraint fk_avaliacao_competencia foreign key (competencia_codigo) references sgc.competencia;

alter table if exists sgc.ocupacao_critica
    add constraint fk_ocupacao_diagnostico foreign key (diagnostico_codigo) references sgc.diagnostico;

alter table if exists sgc.ocupacao_critica
    add constraint fk_ocupacao_servidor foreign key (servidor_titulo) references sgc.vw_usuario;

alter table if exists sgc.ocupacao_critica
    add constraint fk_ocupacao_competencia foreign key (competencia_codigo) references sgc.competencia;
