export const TIPOS_NOTIFICACAO_LABELS: Record<string, string> = {
  PROCESSO_INICIADO: "Início do processo",
  PROCESSO_FINALIZADO: "Finalização do processo",
  DATA_LIMITE_ALTERADA: "Alteração da data limite",
  LEMBRETE_PRAZO: "Lembrete de prazo",
  ATRIBUICAO_TEMPORARIA: "Atribuição temporária",
  CADASTRO_DISPONIBILIZADO: "Cadastro disponibilizado",
  CADASTRO_DEVOLVIDO: "Cadastro devolvido para ajustes",
  CADASTRO_ACEITO: "Cadastro aceito",
  CADASTRO_HOMOLOGADO: "Cadastro homologado",
  CADASTRO_REABERTO: "Cadastro reaberto",
  REVISAO_CADASTRO_DISPONIBILIZADA: "Revisão de cadastro disponibilizada",
  REVISAO_CADASTRO_DEVOLVIDA: "Revisão de cadastro devolvida",
  REVISAO_CADASTRO_ACEITA: "Revisão de cadastro aceita",
  REVISAO_CADASTRO_HOMOLOGADA: "Revisão de cadastro homologada",
  REVISAO_CADASTRO_REABERTA: "Revisão de cadastro reaberta",
  MAPA_DISPONIBILIZADO: "Mapa disponibilizado",
  MAPA_SUGESTOES_APRESENTADAS: "Sugestões apresentadas para o mapa",
  MAPA_VALIDADO: "Mapa validado",
  MAPA_VALIDACAO_DEVOLVIDA: "Validação do mapa devolvida",
  MAPA_VALIDACAO_ACEITA: "Validação do mapa aceita",
  MAPA_HOMOLOGADO: "Mapa homologado",
};
