export const TEXTOS_LOGIN = {
    TITULO: "SGC",
    SUBTITULO: "Sistema de Gestão de Competências",
    LABEL_USUARIO: "Título eleitoral",
    PLACEHOLDER_USUARIO: "Digite seu título",
    LABEL_SENHA: "Senha",
    PLACEHOLDER_SENHA: "Digite sua senha",
    OCULTAR_SENHA: "Ocultar senha",
    MOSTRAR_SENHA: "Mostrar senha",
    CAPS_LOCK: "Caps Lock ativado",
    SELECAO_PERFIL: "Selecione o perfil e a unidade",
    SELECIONE_OPCAO: "-- Selecione uma opção --",
    ENTRANDO: "Entrando...",
    ERRO_CAMPO_TITULO: "Informe o título eleitoral.",
    ERRO_CAMPO_SENHA: "Informe a senha.",
    ERRO_CREDENCIAIS: "Título ou senha inválidos.",
    ERRO_GENERICO: "Ocorreu um erro ao tentar realizar o login.",
    ERRO_SEM_AUTORIZACAO: "Nenhum perfil/unidade disponível para este usuário.",
    ERRO_SELECAO_PERFIL: "Falha ao selecionar o perfil.",
    ERRO_POR_FAVOR_SELECIONE: "Selecione um perfil.",
} as const;
