/**
 * Constantes de textos estáticos do sistema.
 *
 * Centraliza mensagens de sucesso, além de textos recorrentes de views e fluxos
 * de ação em bloco, conforme o plano descrito em msg-report.md.
 */
export const TEXTOS = {
  comum: {
    BOTAO_CONFIRMAR: "Confirmar",
    BOTAO_CANCELAR: "Cancelar",
    BOTAO_SALVAR: "Salvar",
    BOTAO_REMOVER: "Remover",
    BOTAO_ENTRAR: "Entrar",
    BOTAO_CRIAR: "Criar",
    BOTAO_FOR_CADASTRAR: "Cadastrar",
    BOTAO_ATUALIZAR: "Atualizar",
    CARREGANDO: "Carregando...",
    CARREGANDO_DADOS: "Carregando dados...",
    SUCESSO_OPERACAO: "Operação realizada com sucesso",
    ERRO_OPERACAO: "Falha ao realizar operação. Tente novamente.",
    NAO_LIDO: "Não lido: ",
    NENHUM_RESULTADO: "Nenhum resultado encontrado",
    ACAO_NAO_PERMITIDA_SITUACAO: (situacao: string) => `Ação permitida apenas na situação: "${situacao}".`,
  },
  login: {
    TITULO: "SGC",
    SUBTITULO: "Sistema de Gestão de Competências",
    LABEL_USUARIO: "Título eleitoral",
    PLACEHOLDER_USUARIO: "Digite seu título",
    LABEL_SENHA: "Senha",
    PLACEHOLDER_SENHA: "Digite sua senha",
    OCULTAR_SENHA: "Ocultar senha",
    MOSTRAR_SENHA: "Mostrar senha",
    CAPS_LOCK: "Caps Lock ativado",
    SELECAO_PERFIL: "Selecione o perfil e a unidade",
    SELECIONE_OPCAO: "-- Selecione uma opção --",
    ENTRANDO: "Entrando...",
    ERRO_PREENCHIMENTO: "Por favor, preencha título e senha.",
    ERRO_CREDENCIAIS: "Título ou senha inválidos.",
    ERRO_GENERICO: "Ocorreu um erro ao tentar realizar o login.",
    ERRO_SEM_AUTORIZACAO: "Nenhum perfil/unidade disponível para este usuário.",
    ERRO_SELECAO_PERFIL: "Falha ao selecionar o perfil.",
    ERRO_POR_FAVOR_SELECIONE: "Por favor, selecione um perfil.",
  },
  painel: {
    TITULO: "Painel",
    PROCESSOS: "Processos",
    ALERTAS: "Alertas",
    BOTAO_CRIAR_PROCESSO: "Criar processo",
    NENHUM_ALERTA: "Nenhum alerta",
    CAMPOS_ALERTAS: {
      DATA_HORA: "Data/Hora",
      DESCRICAO: "Descrição",
      PROCESSO: "Processo",
      ORIGEM: "Origem",
    },
  },
  mapa: {
    TITULO_TECNICO: "Mapa de competências técnicas",
    BOTAO_IMPACTO: "Impacto no mapa",
    BOTAO_DISPONIBILIZAR: "Disponibilizar",
    BOTAO_CRIAR_PRIMEIRA: "Criar primeira competência",
    BOTAO_CRIAR: "Criar competência",
    EMPTY_DESCRIPTION: "Nenhuma competência cadastrada para esta unidade.",
    EMPTY_TITLE: "Mapa de competências",
    UNIDADE_NAO_ENCONTRADA: "Unidade não encontrada.",
    EXCLUSAO_TITULO: "Exclusão de competência",
    EXCLUSAO_CONFIRMACAO: (desc: string) => `Confirma a exclusão da competência '${desc}'?`,
  },
  atribuicaoTemporaria: {
    TITULO: "Criar atribuição temporária",
    LABEL_USUARIO: "Usuário",
    SELECIONE_USUARIO: "Selecione um usuário",
    LABEL_DATA_INICIO: "Data de Início",
    LABEL_DATA_TERMINO: "Data de Término",
    LABEL_JUSTIFICATIVA: "Justificativa",
    CRIANDO: "Criando...",
    ERRO_CARREGAR: "Falha ao carregar dados da unidade ou usuários.",
    ERRO_SELECIONE_USUARIO: "Selecione um usuário para criar a atribuição.",
    ERRO_PREENCHIMENTO: "Preencha data de início, data de término e justificativa.",
    SUCESSO: "Atribuição criada",
    ERRO_CRIAR: "Falha ao criar atribuição. Tente novamente.",
  },
  unidades: {
    TITULO: "Unidades",
    SUBTITULO: "Clique em unidade para ver detalhes.",
    CARREGANDO: "Carregando unidades...",
    CARREGANDO_ARVORE: "Carregando árvore de unidades...",
    EMPTY_TITLE: "Nenhuma unidade encontrada.",
    EMPTY_DESCRIPTION: "Nenhuma unidade retornada. Tente atualizar a listagem.",
    BOTAO_ATUALIZAR: "Atualizar unidades",
  },
  subprocesso: {
    BOTAO_ALTERAR_DATA_LIMITE: "Alterar data limite",
    BOTAO_REABRIR_CADASTRO: "Reabrir cadastro",
    BOTAO_REABRIR_REVISAO: "Reabrir revisão",
    BOTAO_ENVIAR_LEMBRETE: "Enviar lembrete",
    LABEL_PROCESSO: "Processo",
    LABEL_SITUACAO: "Situação",
    LABEL_LOCALIZACAO: "Localização atual",
    LABEL_PRAZO_ETAPA: "Prazo para conclusão da etapa atual",
    LABEL_TITULAR: "Titular",
    LABEL_RESPONSAVEL: "Responsável",
    MOVIMENTACOES_TITULO: "Movimentações",
    MOVIMENTACOES_VAZIO_TITULO: "Nenhuma movimentação",
    MOVIMENTACOES_VAZIO_TEXTO: "O histórico de movimentações deste processo aparecerá aqui.",
    MOVIMENTACOES_CAMPO_DATA: "Data/hora",
    MOVIMENTACOES_CAMPO_ORIGEM: "Origem",
    MOVIMENTACOES_CAMPO_DESTINO: "Destino",
    MOVIMENTACOES_CAMPO_DESCRICAO: "Descrição",
    CARREGANDO: "Carregando informações da unidade...",
    REABRIR_CADASTRO_TITULO: "Reabrir cadastro",
    REABRIR_REVISAO_TITULO: "Reabrir revisão",
    BOTAO_CONFIRMAR_REABERTURA: "Confirmar reabertura",
    REABRIR_JUSTIFICATIVA_PREFIXO: "Informe a justificativa para reabrir o",
    REABRIR_JUSTIFICATIVA_PLACEHOLDER: "Justificativa obrigatória...",
    CADASTRO: "cadastro",
    REVISAO_CADASTRO: "revisão de cadastro",
    LEMBRETE_TITULO: "Enviar lembrete",
    BOTAO_CONFIRMAR_LEMRETE: "Confirmar envio",
    LEMBRETE_MODELO_PREFIXO: (sigla: string) => `Este lembrete será enviado para os responsáveis da unidade ${sigla}`,
    LEMBRETE_MODELO_PROCESSO: (desc: string) => `sobre o prazo do processo ${desc}.`,
  },
  relatorios: {
    TITULO: "Relatórios",
    ANDAMENTO_PROCESSO: "Andamento de processo",
    MAPAS: "Mapas",
    LABEL_SELECIONE_PROCESSO: "Selecione o Processo",
    LABEL_SELECIONE_UNIDADE: "Selecione a unidade",
    BOTAO_GERAR: "Gerar relatório",
    BOTAO_GERANDO: "Gerando...",
    BOTAO_PDF: "Sair em PDF",
    BOTAO_GERAR_PDF: "Gerar PDF",
    EMPTY_TITLE: "Relatório de Andamento",
    EMPTY_DESCRIPTION: "Nenhum dado encontrado ou relatório ainda não gerado.",
    SELECIONE: "Selecione...",
    TODAS_UNIDADES: "Todas as unidades (processo inteiro)",
    ERRO_BUSCA: "Erro ao buscar relatório",
    ERRO_EXPORTAR: "Erro ao exportar PDF",
    ERRO_GERAR: "Erro ao gerar PDF",
  },
  administracao: {
    TITULO: "Administradores",
    BOTAO_ADICIONAR: "Adicionar administrador",
    EMPTY_TITLE: "Nenhum administrador cadastrado",
    EMPTY_DESCRIPTION: "Utilize o botão 'Adicionar administrador' para cadastrar novos administradores.",
    LABEL_TITULO: "Título",
    PLACEHOLDER_TITULO: "Digite o título eleitoral",
    MODAL_ADICIONAR_TITULO: "Adicionar administrador",
    MODAL_REMOVER_TITULO: "Confirmar remoção",
    MODAL_REMOVER_PERGUNTA: (nome: string) => `Deseja realmente remover ${nome} como administrador do sistema?`,
    CAMPO_NOME: "Nome",
    CAMPO_TITULO: "Título eleitoral",
    CAMPO_MATRICULA: "Matrícula",
    CAMPO_UNIDADE: "Unidade",
    CAMPO_ACOES: "Ações",
    ERRO_TITULO_INVALIDO: "Digite um título eleitoral válido",
    SUCESSO_ADICIONADO: "Administrador adicionado",
    SUCESSO_REMOVIDO: "Administrador removido",
  },
  atividades: {
    TITULO: "Atividades e conhecimentos",
    BOTAO_IMPACTO: "Impacto no mapa",
    BOTAO_HISTORICO: "Histórico",
    BOTAO_IMPORTAR: "Importar",
    BOTAO_DISPONIBILIZAR: "Disponibilizar",
    BOTAO_DISPONIBILIZANDO: "Validando...",
    EMPTY_TITLE: "Lista de atividades",
    EMPTY_DESCRIPTION: "Não há atividades cadastradas. Utilize o campo acima para adicionar uma nova atividade ou importe de outro processo.",
    MODAL_REMOVER_ATIVIDADE_TITULO: "Remover atividade",
    MODAL_REMOVER_ATIVIDADE_TEXTO: "Confirma a remoção desta atividade e todos os conhecimentos associados?",
    MODAL_REMOVER_CONHECIMENTO_TITULO: "Remover conhecimento",
    MODAL_REMOVER_CONHECIMENTO_TEXTO: "Confirma a remoção deste conhecimento?",
    ERRO_ADICIONAR: "Não foi possível adicionar atividade.",
    ERRO_REMOVER: "Não foi possível remover o item.",
    ERRO_SALVAR_ATIVIDADE: "Falha ao salvar edição da atividade.",
    ERRO_ADICIONAR_CONHECIMENTO: "Falha ao adicionar conhecimento.",
    ERRO_ATUALIZAR_CONHECIMENTO: "Falha ao atualizar conhecimento.",
    SUCESSO_IMPORTACAO: "As atividades foram importadas para o seu mapa.",
  },
  unidade: {
    BOTAO_MAPA_VIGENTE: "Mapa vigente",
    BOTAO_CRIAR_ATRIBUICAO: "Criar atribuição",
    LABEL_TITULAR: "Titular:",
    LABEL_RESPONSAVEL: "Responsável:",
    LABEL_RAMAL: "Ramal:",
    LABEL_EMAIL: "E-mail:",
    NAO_INFORMADO: "Não informado",
    SUBORDINADAS_TITULO: "Unidades subordinadas",
    CAMPO_UNIDADE: "Unidade",
    EMPTY_TITLE: "Unidade não encontrada",
    EMPTY_DESCRIPTION: "Não foi possível localizar os dados da unidade solicitada.",
    ERRO_CARREGAR: "Erro ao carregar unidade",
  },
  sucesso: {
    ACEITE_REGISTRADO: "Aceite registrado",
    ACAO_EM_BLOCO_REALIZADA: "Ação em bloco realizada",
    ACEITES_REGISTRADOS_EM_BLOCO: "Aceites registrados em bloco",
    CADASTRO_ATIVIDADES_DISPONIBILIZADO: "Cadastro de atividades disponibilizado",
    CADASTROS_ACEITOS_EM_BLOCO: "Cadastros aceitos em bloco",
    CADASTROS_HOMOLOGADOS_EM_BLOCO: "Cadastros homologados em bloco",
    DEVOLUCAO_REALIZADA: "Devolução realizada",
    HOMOLOGACAO_EFETIVADA: "Homologação efetivada",
    HOMOLOGACOES_REGISTRADAS_EM_BLOCO: "Homologações registradas em bloco",
    MAPA_DISPONIBILIZADO: "Disponibilização do mapa de competências efetuada",
    MAPA_SUBMETIDO_COM_SUGESTOES: "Mapa submetido com sugestões para análise da unidade superior",
    MAPA_VALIDADO_SUBMETIDO: "Mapa validado e submetido para análise à unidade superior",
    MAPAS_ACEITOS_EM_BLOCO: "Mapas aceitos em bloco",
    MAPAS_DISPONIBILIZADOS_EM_BLOCO: "Mapas de competências disponibilizados em bloco",
    MAPAS_HOMOLOGADOS_EM_BLOCO: "Mapas de competências homologados em bloco",
    PROCESSO_ALTERADO: "Processo alterado.",
    PROCESSO_CRIADO: "Processo criado.",
    PROCESSO_FINALIZADO: "Processo finalizado",
    PROCESSO_INICIADO: "Processo iniciado",
    PROCESSO_REMOVIDO: (descricao: string) => `Processo ${descricao} removido`,
    REVISAO_CADASTRO_ATIVIDADES_DISPONIBILIZADA: "Revisão do cadastro de atividades disponibilizada",
  },
  processo: {
    CONCLUIDO: "Processo concluído.",
    FINALIZAR: "Finalizar processo",
    CARREGANDO_DETALHES: "Carregando detalhes do processo...",
    ERRO_PADRAO: "Ocorreu um erro",
    FINALIZACAO_TITULO: "Finalização de processo",
    FINALIZACAO_CONFIRMACAO_PREFIXO: "Confirma a finalização do processo",
    FINALIZACAO_CONFIRMACAO_COMPLEMENTO:
      "Essa ação tornará vigentes os mapas de competências homologados e notificará todas as unidades participantes do processo.",
    ERRO_ACAO_BLOCO: "Erro ao executar ação em bloco",
    cadastro: {
      TITULO: "Cadastro de processo",
      BOTAO_INICIAR: "Iniciar processo",
      BOTAO_SALVAR: "Salvar",
      BOTAO_REMOVER: "Remover",
      BOTAO_CANCELAR: "Cancelar",
      INICIAR_TITULO: "Iniciar processo",
      INICIAR_CONFIRMACAO: "Ao iniciar o processo, não será mais possível editá-lo ou removê-lo e todas as unidades participantes serão notificadas por e-mail.",
      REMOVER_TITULO: "Remover processo",
      REMOVER_CONFIRMACAO: (desc: string) => `Remover o processo '${desc}'? Esta ação não poderá ser desfeita.`,
      ERRO_CARREGAR_DETALHES: "Não foi possível carregar os detalhes do processo.",
      ERRO_CRIAR_PARA_INICIAR: "Não foi possível criar o processo para iniciá-lo.",
      ERRO_INICIAR_PROCESSO: "Não foi possível iniciar o processo. Tente novamente.",
      ERRO_REMOVER_PROCESSO: "Não foi possível remover o processo. Tente novamente.",
    },
  },
  acaoBloco: {
    aceitar: {
      ROTULO_CADASTRO: "Aceitar cadastro em bloco",
      ROTULO_VALIDACAO: "Aceitar mapas em bloco",
      ROTULO_MISTO: "Registrar aceite em bloco",
      TITULO_CADASTRO: "Aceite de cadastro em bloco",
      TITULO_VALIDACAO: "Aceite de mapas em bloco",
      TITULO_MISTO: "Aceite em bloco",
      TEXTO_CADASTRO: "Selecione as unidades cujos cadastros deverão ser aceitos:",
      TEXTO_VALIDACAO: "Selecione as unidades para aceite dos mapas correspondentes",
      TEXTO_MISTO: "Selecione as unidades para registrar o aceite correspondente.",
      BOTAO: "Registrar aceite",
    },
    homologar: {
      ROTULO_CADASTRO: "Homologar em bloco",
      ROTULO_VALIDACAO: "Homologar mapa de competências em bloco",
      ROTULO_MISTO: "Homologar em bloco",
      TITULO_CADASTRO: "Homologação de cadastro em bloco",
      TITULO_VALIDACAO: "Homologação de mapa em bloco",
      TITULO_MISTO: "Homologação em bloco",
      TEXTO_CADASTRO: "Selecione abaixo as unidades cujos cadastros deverão ser homologados:",
      TEXTO_VALIDACAO: "Selecione abaixo as unidades cujos mapas deverão ser homologados:",
      TEXTO_MISTO: "Selecione as unidades para homologação em bloco.",
      BOTAO: "Homologar",
    },
    disponibilizar: {
      ROTULO: "Disponibilizar mapas em bloco",
      TITULO: "Disponibilização de mapa em bloco",
      TEXTO: "Selecione abaixo as unidades cujos mapas deverão ser disponibilizados:",
      BOTAO: "Disponibilizar",
    },
  },
} as const;

export type Textos = typeof TEXTOS;
