export const TEXTOS_COMUM = {
    BOTAO_CANCELAR: "Cancelar",
    BOTAO_REMOVER: "Remover",
    BOTAO_EDITAR: "Editar",
    BOTAO_ENTRAR: "Entrar",
    BOTAO_CRIAR: "Criar",
    BOTAO_SALVAR: "Salvar",
    BOTAO_INICIAR: "Iniciar",
    BOTAO_HOMOLOGAR: "Homologar",
    BOTAO_REGISTRAR_ACEITE: "Registrar aceite",
    BOTAO_VALIDAR: "Validar",
    BOTAO_DEVOLVER: "Devolver",
    BOTAO_REABRIR: "Reabrir",
    BOTAO_APRESENTAR: "Apresentar",
    BOTAO_FINALIZAR: "Finalizar",
    BOTAO_DISPONIBILIZAR: "Disponibilizar",
    CARREGANDO: "Carregando...",
    CARREGANDO_DADOS: "Carregando dados...",
    ERRO_OPERACAO: "Falha ao realizar operação. Tente novamente.",
    NAO_LIDO: "Não lido: ",
    ACAO_NAO_PERMITIDA_SITUACAO: (situacao: string) => `Ação permitida apenas na situação: "${situacao}".`,
    NOME_SISTEMA: "SGC",
    MENU_PAINEL: "Painel",
    MENU_UNIDADES: "Unidades",
    MENU_MINHA_UNIDADE: "Minha unidade",
    MENU_RELATORIOS: "Relatórios",
    MENU_HISTORICO: "Histórico",
    MENU_NOTIFICACOES: "Notificações",
    MENU_FEEDBACKS: "Feedbacks",
    RODAPE: "© SESEL/COSIS/TRE-PE",
    VERSAO: "Versão",
    PULAR_CONTEUDO: "Pular para o conteúdo principal",
    BOTAO_FECHAR: "Fechar",
    BOTAO_VOLTAR: "Voltar",
    OBSERVACAO: "Observações",
} as const;
