export const TEXTOS_MAPA = {
    TITULO: "Mapa de competências",
    TITULO_TECNICO: "Mapa de competências técnicas",
    BOTAO_IMPACTO: "Impacto no mapa",
    BOTAO_DISPONIBILIZAR: "Disponibilizar",
    BOTAO_CRIAR: "Criar competência",
    EMPTY_TITLE: "Mapa vazio",
    EMPTY_DESCRIPTION: "Adicione competências para começar a montar o mapa da unidade.",
    UNIDADE_NAO_ENCONTRADA: "Unidade não encontrada.",
    ERRO_MAPA_SEM_COMPETENCIAS: "O mapa deve ter pelo menos uma competência para ser disponibilizado.",
    ERRO_COMPETENCIA_SEM_ATIVIDADE: "Existem competências sem nenhuma atividade associada. Corrija-as antes de disponibilizar.",
    ERRO_ATIVIDADES_SEM_COMPETENCIA: "Existem atividades do cadastro que não foram associadas a nenhuma competência do mapa.",
    EXCLUSAO_TITULO: "Exclusão de competência",
    EXCLUSAO_CONFIRMACAO: (desc: string) => `Confirma a exclusão da competência '${desc}'?`,
    BOTAO_SUGESTOES: "Apresentar sugestões",
    BOTAO_VALIDAR: "Validar",
    BOTAO_VER_SUGESTOES: "Ver sugestões",
    BOTAO_ACOES: "Ações",
    BOTAO_EXPORTAR: "Exportar",
    BOTAO_HISTORICO_ANALISE: "Histórico de análise",
    BOTAO_DEVOLVER: "Devolver ",
    LABEL_HOMOLOGAR: "Homologar",
    LABEL_REGISTRAR_ACEITE: "Registrar aceite",
    MODAL_ACEITE_TITULO: "Aceitar mapa",
    MODAL_ACEITE_TEXTO: "Confirma o aceite da validação do mapa?",
    MODAL_HOMOLOGAR_TITULO: "Homologar mapa",
    MODAL_HOMOLOGAR_TEXTO: "Confirma a homologação do mapa?",
    SUCESSO_HOMOLOGACAO: "Mapa homologado",
    ERRO_SUGESTOES: "Erro ao apresentar sugestões",
    ERRO_VALIDAR: "Erro ao validar o mapa",
    ERRO_DEVOLVER: "Erro ao devolver",
    impacto: {
        TITULO_MODAL: "Impacto no Mapa de Competências",
        VERIFICANDO: "Verificando impactos...",
        SEM_IMPACTOS: "Nenhum impacto no mapa da unidade.",
        ATIVIDADES_INSERIDAS: "Atividades inseridas",
        ATIVIDADES_REMOVIDAS: "Atividades removidas",
        ATIVIDADES_ALTERADAS: "Atividades alteradas",
        COMPETENCIAS_IMPACTADAS: "Competências impactadas",
        IMPACTADA_POR: "Impactada por: ",
        TIPOS_IMPACTO: "Tipos de Impacto: ",
        ERRO_CARREGAR: "Não foi possível carregar os dados de impacto.",
        TIPO_REMOVIDA: "Atividade removida",
        TIPO_ALTERADA: "Atividade alterada",
        CONHECIMENTOS_ADICIONADOS: "Conhecimentos adicionados",
        CONHECIMENTOS_REMOVIDOS: "Conhecimentos removidos",
        COMPETENCIA_REMOVIDA: "Competência removida",
        COMPETENCIA_INSERIDA: "Nova competência",
    },
} as const;

export const TEXTOS_MAPA_VISUALIZACAO = {
    EMPTY_TITLE: "Mapa sem competências",
    EMPTY_DESCRIPTION: "Este mapa ainda não recebeu competências registradas.",
} as const;

export const TEXTOS_SUCESSO_MAPA = {
    MAPA_DISPONIBILIZADO: "Mapa de competências disponibilizado",
    MAPA_SUBMETIDO_COM_SUGESTOES: "Mapa submetido com sugestões para análise da unidade superior",
    MAPA_VALIDADO_SUBMETIDO: "Mapa validado e submetido para análise à unidade superior",
} as const;
