export const TEXTOS_ATRIBUICAO_TEMPORARIA = {
    TITULO: "Atribuição temporária",
    TITULO_EDICAO: "Editar atribuição temporária",
    LABEL_USUARIO: "Usuário",
    SELECIONE_USUARIO: "Selecione um usuário",
    AJUDA_PESQUISA_USUARIO: "Pesquise por nome ou título eleitoral.",
    BUSCANDO_USUARIOS: "Buscando usuários...",
    NENHUM_USUARIO_ENCONTRADO: "Nenhum usuário encontrado.",
    LABEL_DATA_INICIO: "Data de início",
    LABEL_DATA_TERMINO: "Data de término",
    LABEL_JUSTIFICATIVA: "Justificativa",
    CRIANDO: "Criando...",
    SALVANDO: "Salvando...",
    REMOVENDO: "Removendo...",
    ERRO_CARREGAR: "Falha ao carregar dados da unidade ou usuários.",
    ERRO_SELECIONE_USUARIO: "Selecione um usuário para criar a atribuição.",
    SUCESSO: "Atribuição criada",
    SUCESSO_ATUALIZACAO: "Atribuição atualizada",
    SUCESSO_REMOCAO: "Atribuição removida",
    ERRO_CRIAR: "Falha ao criar atribuição. Tente novamente.",
    ERRO_ATUALIZAR: "Falha ao atualizar atribuição. Tente novamente.",
    ERRO_REMOVER: "Falha ao remover atribuição. Tente novamente.",
    ERRO_CARREGAR_ATRIBUICOES: "Falha ao carregar atribuições temporárias da unidade.",
    BOTAO_REMOVER: "Remover",
    MODAL_REMOVER_TITULO: "Remover atribuição temporária",
    MODAL_REMOVER_TEXTO: "Confirma a remoção da atribuição temporária vigente desta unidade?",
} as const;

export const TEXTOS_ADMINISTRACAO = {
    TITULO: "Administradores",
    BOTAO_ADICIONAR: "Adicionar",
    EMPTY_TITLE: "Sem administradores cadastrados",
    EMPTY_DESCRIPTION: "Use o botão de adicionar para incluir o primeiro administrador.",
    PLACEHOLDER_TITULO: "Digite nome ou título",
    MODAL_ADICIONAR_TITULO: "Adicionar administrador",
    MODAL_REMOVER_TITULO: "Confirmar remoção",
    MODAL_REMOVER_PERGUNTA: (nome: string) => `Deseja realmente remover ${nome} como administrador do sistema?`,
    CAMPO_NOME: "Nome",
    CAMPO_TITULO: "Título eleitoral",
    CAMPO_MATRICULA: "Matrícula",
    CAMPO_UNIDADE: "Unidade",
    CAMPO_ACOES: "Ações",
    ERRO_TITULO_INVALIDO: "Digite um título eleitoral válido",
    SUCESSO_ADICIONADO: "Administrador adicionado",
    SUCESSO_REMOVIDO: "Administrador removido",
    BOTAO_LIMPEZA_PROCESSOS: "Limpeza de processos",
    LIMPEZA_TITULO: "Limpeza de processos",
    LIMPEZA_ALERTA: "Esta operação remove o processo e todos os seus dependentes. Use somente em homologação e apenas para dados de teste.",
    LIMPEZA_LABEL_CODIGO: "Código do processo",
    LIMPEZA_PLACEHOLDER_CODIGO: "Digite o código do processo",
    LIMPEZA_BOTAO_ABRIR: "Excluir processo",
    LIMPEZA_MODAL_TITULO: "Confirmar exclusão completa",
    LIMPEZA_MODAL_TEXTO: (codigo: number) => `Confirma a exclusão completa do processo ${codigo} e de todos os seus dependentes?`,
    LIMPEZA_SUCESSO: "Processo removido com sucesso",
    LIMPEZA_ERRO_CODIGO: "Informe um código de processo válido",
    NOTIFICACOES_SEM_REGISTROS: "Sem notificações",
    NOTIFICACOES_ATUALIZAR: "Atualizar",
    NOTIFICACOES_REENVIAR: "Reenviar",
    NOTIFICACOES_DETALHES: "Detalhes",
    NOTIFICACOES_PREVIEW_DESTINATARIO: "Para",
    NOTIFICACOES_PREVIEW_CRIACAO: "Criado em",
    NOTIFICACOES_MODAL_REENVIAR_TITULO: "Reenviar e-mail",
    NOTIFICACOES_ERRO_CARREGAR: "Não foi possível carregar as notificações",
    NOTIFICACOES_SUCESSO_REENVIO: "E-mail recolocado na fila de envio",
    NOTIFICACOES_ERRO_REENVIO: "Erro ao reenviar e-mail",
    NOTIFICACOES_CAMPOS: {
        DESTINATARIO: "Destinatário",
        PROCESSO: "Processo",
        TIPO: "Tipo",
        STATUS: "Situação",
        QUANDO: "Quando",
        ERRO: "Erro",
        PROXIMA_TENTATIVA: "Próxima",
        CONCLUSAO: "Conclusão",
        ACOES: "Ações",
    },
    FEEDBACKS_TITULO: "Feedbacks",
    FEEDBACKS_ATUALIZAR: "Atualizar",
    FEEDBACKS_SEM_REGISTROS: "Nenhum feedback registrado",
    FEEDBACKS_ERRO_CARREGAR: "Não foi possível carregar os feedbacks",
    FEEDBACKS_MODAL_TITULO: "Detalhes do feedback",
    FEEDBACKS_CAMPOS: {
        TIPO: "Tipo",
        STATUS: "Situação",
        USUARIO: "Usuário",
        ROTA: "Rota",
        ENVIADO_EM: "Enviado em",
        NOTA: "Descrição",
        CAPTURA: "Captura",
        METADADOS: "Metadados",
        ACOES: "Ações",
    },
} as const;

export const TEXTOS_CONFIGURACOES = {
    TITULO: "Configurações",
    LABEL_DIAS_INATIVACAO: "Dias para inativação de processos",
    DESC_DIAS_INATIVACAO: "Dias depois da finalização de um processo para que seja considerado inativo.",
    LABEL_DIAS_ALERTA_NOVO: "Dias para indicação de alerta como não lido",
    DESC_DIAS_ALERTA_NOVO: "Dias depois de um alerta ser enviado para que deixe de ser destacado.",
    LABEL_TEMA_ESCURO: "Habilitar tema escuro neste navegador",
    DESC_TEMA_ESCURO: "Quando ativado, o sistema utilizará cores escuras apenas neste navegador e dispositivo.",
    SUCESSO_SALVAR: "Configurações salvas.",
    ERRO_SALVAR: "Erro ao salvar configurações.",
    BOTAO_SALVAR: "Salvar",
} as const;
