/**
 * Constantes de textos estáticos do sistema.
 *
 * Centraliza mensagens de sucesso, além de textos recorrentes de views e fluxos
 * de ação em bloco, conforme o plano descrito em msg-report.md.
 */
export const TEXTOS = {
  comum: {
    BOTAO_CONFIRMAR: "Confirmar",
    BOTAO_CANCELAR: "Cancelar",
    BOTAO_SALVAR: "Salvar",
    BOTAO_REMOVER: "Remover",
    BOTAO_ENTRAR: "Entrar",
    BOTAO_CRIAR: "Criar",
    BOTAO_FOR_CADASTRAR: "Cadastrar",
    BOTAO_ATUALIZAR: "Atualizar",
    BOTAO_INICIAR: "Iniciar",
    BOTAO_HOMOLOGAR: "Homologar",
    BOTAO_ACEITAR: "Aceitar",
    BOTAO_VALIDAR: "Validar",
    BOTAO_DEVOLVER: "Devolver",
    BOTAO_REABRIR: "Reabrir",
    BOTAO_APRESENTAR: "Apresentar",
    BOTAO_FINALIZAR: "Finalizar",
    BOTAO_DISPONIBILIZAR: "Disponibilizar",
    BOTAO_EXCLUIR: "Excluir",
    BOTAO_ENVIAR: "Enviar",
    CARREGANDO: "Carregando...",
    CARREGANDO_DADOS: "Carregando dados...",
    SUCESSO_OPERACAO: "Operação realizada com sucesso",
    ERRO_OPERACAO: "Falha ao realizar operação. Tente novamente.",
    NAO_LIDO: "Não lido: ",
    NENHUM_RESULTADO: "Nenhum resultado encontrado",
    ACAO_NAO_PERMITIDA_SITUACAO: (situacao: string) => `Ação permitida apenas na situação: "${situacao}".`,
    NOME_SISTEMA: "SGC",
    MENU_PAINEL: "Painel",
    MENU_UNIDADES: "Unidades",
    MENU_MINHA_UNIDADE: "Minha unidade",
    MENU_RELATORIOS: "Relatórios",
    MENU_HISTORICO: "Histórico",
    RODAPE: "© SESEL/COSIS/TRE-PE",
    VERSAO: "Versão",
    PULAR_CONTEUDO: "Pular para o conteúdo principal",
    BOTAO_FECHAR: "Fechar",
    OBSERVACAO: "Observação",
  },
  login: {
    TITULO: "SGC",
    SUBTITULO: "Sistema de Gestão de Competências",
    LABEL_USUARIO: "Título eleitoral",
    PLACEHOLDER_USUARIO: "Digite seu título",
    LABEL_SENHA: "Senha",
    PLACEHOLDER_SENHA: "Digite sua senha",
    OCULTAR_SENHA: "Ocultar senha",
    MOSTRAR_SENHA: "Mostrar senha",
    CAPS_LOCK: "Caps Lock ativado",
    SELECAO_PERFIL: "Selecione o perfil e a unidade",
    SELECIONE_OPCAO: "-- Selecione uma opção --",
    ENTRANDO: "Entrando...",
    ERRO_PREENCHIMENTO: "Por favor, preencha título e senha.",
    ERRO_CREDENCIAIS: "Título ou senha inválidos.",
    ERRO_GENERICO: "Ocorreu um erro ao tentar realizar o login.",
    ERRO_SEM_AUTORIZACAO: "Nenhum perfil/unidade disponível para este usuário.",
    ERRO_SELECAO_PERFIL: "Falha ao selecionar o perfil.",
    ERRO_POR_FAVOR_SELECIONE: "Por favor, selecione um perfil.",
  },
  painel: {
    TITULO: "Painel",
    PROCESSOS: "Processos",
    ALERTAS: "Alertas",
    BOTAO_CRIAR_PROCESSO: "Criar processo",
    NENHUM_ALERTA: "Nenhum alerta",
    CAMPOS_ALERTAS: {
      DATA_HORA: "Data/Hora",
      DESCRICAO: "Descrição",
      PROCESSO: "Processo",
      ORIGEM: "Origem",
    },
  },
  mapa: {
    TITULO: "Mapa de competências",
    TITULO_TECNICO: "Mapa de competências técnicas",
    BOTAO_IMPACTO: "Impacto no mapa",
    BOTAO_DISPONIBILIZAR: "Disponibilizar",
    BOTAO_CRIAR_PRIMEIRA: "Criar primeira competência",
    BOTAO_CRIAR: "Criar competência",
    EMPTY_DESCRIPTION: "Nenhuma competência cadastrada para a unidade.",
    EMPTY_TITLE: "Mapa de competências",
    UNIDADE_NAO_ENCONTRADA: "Unidade não encontrada.",
    EXCLUSAO_TITULO: "Exclusão de competência",
    EXCLUSAO_CONFIRMACAO: (desc: string) => `Confirma a exclusão da competência '${desc}'?`,
    BOTAO_SUGESTOES: "Apresentar sugestões",
    BOTAO_VALIDAR: "Validar",
    BOTAO_VER_SUGESTOES: "Ver sugestões",
    BOTAO_HISTORICO_ANALISE: "Histórico de análise",
    BOTAO_DEVOLVER: "Devolver",
    BOTAO_ACEITAR: "Aceitar",
    LABEL_HOMOLOGAR: "Homologar",
    LABEL_REGISTRAR_ACEITE: "Registrar aceite",
    MODAL_ACEITE_TITULO: "Aceitar mapa",
    MODAL_ACEITE_TEXTO: "Confirma o aceite da validação do mapa de competências?",
    MODAL_HOMOLOGAR_TITULO: "Homologar mapa",
    MODAL_HOMOLOGAR_TEXTO: "Confirma a homologação do mapa de competências?",
    SUCESSO_DEVOLUCAO: "Devolução realizada",
    SUCESSO_VALIDACAO: "Mapa validado",
    SUCESSO_ACEITE: "Aceite registrado",
    SUCESSO_HOMOLOGACAO: "Mapa homologado",
    ERRO_SUGESTOES: "Erro ao apresentar sugestões",
    ERRO_VALIDAR: "Erro ao validar o mapa",
    ERRO_DEVOLVER: "Erro ao devolver",
    impacto: {
      TITULO_MODAL: "Impacto no Mapa de Competências",
      VERIFICANDO: "Verificando impactos...",
      SEM_IMPACTOS: "Nenhum impacto no mapa da unidade.",
      ATIVIDADES_INSERIDAS: "Atividades inseridas",
      ATIVIDADES_REMOVIDAS: "Atividades removidas",
      ATIVIDADES_ALTERADAS: "Atividades alteradas",
      COMPETENCIAS_IMPACTADAS: "Competências impactadas",
      IMPACTADA_POR: "Impactada por: ",
      TIPOS_IMPACTO: "Tipos de Impacto: ",
      ERRO_CARREGAR: "Não foi possível carregar os dados de impacto.",
      TIPO_REMOVIDA: "Atividade removida",
      TIPO_ALTERADA: "Atividade alterada",
    },
  },
  atribuicaoTemporaria: {
    TITULO: "Criar atribuição temporária",
    LABEL_USUARIO: "Usuário",
    SELECIONE_USUARIO: "Selecione um usuário",
    AJUDA_PESQUISA_USUARIO: "Pesquise por nome ou título eleitoral.",
    BUSCANDO_USUARIOS: "Buscando usuários...",
    NENHUM_USUARIO_ENCONTRADO: "Nenhum usuário encontrado.",
    TITULO_ELEITORAL: "Título eleitoral",
    BOTAO_ALTERAR_USUARIO: "Alterar",
    LABEL_DATA_INICIO: "Data de Início",
    LABEL_DATA_TERMINO: "Data de Término",
    LABEL_JUSTIFICATIVA: "Justificativa",
    CRIANDO: "Criando...",
    ERRO_CARREGAR: "Falha ao carregar dados da unidade ou usuários.",
    ERRO_SELECIONE_USUARIO: "Selecione um usuário para criar a atribuição.",
    ERRO_PREENCHIMENTO: "Preencha data de início, data de término e justificativa.",
    SUCESSO: "Atribuição criada",
    ERRO_CRIAR: "Falha ao criar atribuição. Tente novamente.",
  },
  unidades: {
    TITULO: "Unidades",
    SUBTITULO: "Clique em unidade para ver detalhes.",
    CARREGANDO: "Carregando unidades...",
    CARREGANDO_ARVORE: "Carregando árvore de unidades...",
    EMPTY_TITLE: "Nenhuma unidade encontrada.",
    EMPTY_DESCRIPTION: "Nenhuma unidade retornada. Tente atualizar a listagem.",
    BOTAO_ATUALIZAR: "Atualizar unidades",
  },
  subprocesso: {
    BOTAO_ALTERAR_DATA_LIMITE: "Alterar data limite",
    BOTAO_REABRIR_CADASTRO: "Reabrir cadastro",
    BOTAO_REABRIR_REVISAO: "Reabrir revisão",
    BOTAO_ENVIAR_LEMBRETE: "Enviar lembrete",
    LABEL_PROCESSO: "Processo",
    LABEL_SITUACAO: "Situação",
    LABEL_LOCALIZACAO: "Localização atual",
    LABEL_PRAZO_ETAPA: "Prazo para conclusão da etapa atual",
    LABEL_TITULAR: "Titular",
    LABEL_RESPONSAVEL: "Responsável",
    MOVIMENTACOES_TITULO: "Movimentações",
    MOVIMENTACOES_VAZIO_TITULO: "Nenhuma movimentação",
    MOVIMENTACOES_VAZIO_TEXTO: "O histórico de movimentações deste processo aparecerá aqui.",
    MOVIMENTACOES_CAMPO_DATA: "Data/hora",
    MOVIMENTACOES_CAMPO_ORIGEM: "Origem",
    MOVIMENTACOES_CAMPO_DESTINO: "Destino",
    MOVIMENTACOES_CAMPO_DESCRICAO: "Descrição",
    ERRO_SEM_PERMISSAO_DATA: "Você não tem permissão para alterar a data limite.",
    SUCESSO_DATA_ALTERADA: "Data limite alterada",
    ERRO_DATA_ALTERADA: "Não foi possível alterar a data limite",
    ERRO_JUSTIFICATIVA_OBRIGATORIA: "Justificativa é obrigatória",
    SUCESSO_CADASTRO_REABERTO: "Cadastro reaberto",
    SUCESSO_REVISAO_REABERTA: "Revisão reaberta",
    SUCESSO_LEMBRETE_ENVIADO: "Lembrete enviado",
    ERRO_LEMBRETE_ENVIADO: "Não foi possível enviar o lembrete",
    CARREGANDO: "Carregando informações da unidade...",
    REABRIR_CADASTRO_TITULO: "Reabrir cadastro",
    REABRIR_REVISAO_TITULO: "Reabrir revisão",
    BOTAO_CONFIRMAR_REABERTURA: "Confirmar reabertura",
    REABRIR_JUSTIFICATIVA_PREFIXO: "Informe a justificativa para reabrir o",
    REABRIR_JUSTIFICATIVA_PLACEHOLDER: "Justificativa obrigatória...",
    CADASTRO: "cadastro",
    REVISAO_CADASTRO: "revisão de cadastro",
    LEMBRETE_TITULO: "Enviar lembrete",
    BOTAO_CONFIRMAR_LEMBRETE: "Enviar",
    LEMBRETE_MODELO_PREFIXO: (sigla: string) => `Confirma envio de lembrete para a unidade ${sigla}?`,
    DETALHE_UNIDADES_TITULO: "Unidades participantes",
    COLUNA_UNIDADE: "Unidade",
    COLUNA_SITUACAO: "Situação",
    COLUNA_DATA_LIMITE: "Data limite",
    cards: {
      ATUALIZACAO_CADASTRO_TITULO: "Atividades e conhecimentos",
      ATUALIZACAO_CADASTRO_TEXTO: "Cadastro de atividades e conhecimentos da unidade",
      VISUALIZACAO_CADASTRO_TEXTO: "Visualização das atividades e conhecimentos da unidade",
      MAPA_TITULO: "Mapa de Competências",
      MAPA_TEXTO: "Mapa de competências técnicas da unidade",
      MAPA_VISUALIZACAO_TEXTO: "Visualização do mapa de competências técnicas",
      AUTOAVALIACAO_TITULO: "Autoavaliação",
      AUTOAVALIACAO_TEXTO: "Realize sua autoavaliação de competências",
      OCUPACOES_TITULO: "Ocupações críticas",
      OCUPACOES_TEXTO: "Identificação das ocupações críticas da unidade",
      MONITORAMENTO_TITULO: "Monitoramento",
      MONITORAMENTO_TEXTO: "Acompanhamento e conclusão do diagnóstico da unidade",
    },
    NAO_ENCONTRADO_TITULO: "Subprocesso não iniciado",
    NAO_ENCONTRADO_DESC: "Este subprocesso ainda não foi iniciado ou a unidade não participa deste processo.",
  },
  relatorios: {
    TITULO: "Relatórios",
    ANDAMENTO_PROCESSO: "Andamento de processo",
    MAPAS: "Mapas",
    LABEL_SELECIONE_PROCESSO: "Selecione o Processo",
    LABEL_SELECIONE_UNIDADE: "Selecione a unidade",
    BOTAO_GERAR: "Gerar relatório",
    BOTAO_GERANDO: "Gerando...",
    BOTAO_PDF: "Sair em PDF",
    BOTAO_GERAR_PDF: "Gerar PDF",
    EMPTY_TITLE: "Relatório de Andamento",
    EMPTY_DESCRIPTION: "Nenhum dado encontrado ou relatório ainda não gerado.",
    SELECIONE: "Selecione...",
    TODAS_UNIDADES: "Todas as unidades (processo inteiro)",
    ERRO_BUSCA: "Erro ao buscar relatório",
    ERRO_EXPORTAR: "Erro ao exportar PDF",
    ERRO_GERAR: "Erro ao gerar PDF",
  },
  administracao: {
    TITULO: "Administradores",
    BOTAO_ADICIONAR: "Adicionar administrador",
    EMPTY_TITLE: "Nenhum administrador cadastrado",
    EMPTY_DESCRIPTION: "Utilize o botão 'Adicionar administrador' para cadastrar novos administradores.",
    LABEL_TITULO: "Título",
    PLACEHOLDER_TITULO: "Digite o título eleitoral",
    MODAL_ADICIONAR_TITULO: "Adicionar administrador",
    MODAL_REMOVER_TITULO: "Confirmar remoção",
    MODAL_REMOVER_PERGUNTA: (nome: string) => `Deseja realmente remover ${nome} como administrador do sistema?`,
    CAMPO_NOME: "Nome",
    CAMPO_TITULO: "Título eleitoral",
    CAMPO_MATRICULA: "Matrícula",
    CAMPO_UNIDADE: "Unidade",
    CAMPO_ACOES: "Ações",
    ERRO_TITULO_INVALIDO: "Digite um título eleitoral válido",
    SUCESSO_ADICIONADO: "Administrador adicionado",
    SUCESSO_REMOVIDO: "Administrador removido",
  },
  atividades: {
    TITULO: "Atividades e conhecimentos",
    BOTAO_IMPACTO: "Impacto no mapa",
    BOTAO_HISTORICO: "Histórico",
    BOTAO_IMPORTAR: "Importar",
    BOTAO_DISPONIBILIZAR: "Disponibilizar",
    BOTAO_DISPONIBILIZANDO: "Validando...",
    EMPTY_TITLE: "Lista de atividades",
    EMPTY_DESCRIPTION: "Não há atividades cadastradas. Utilize o campo acima para adicionar uma nova atividade ou importe de outro processo.",
    MODAL_REMOVER_ATIVIDADE_TITULO: "Remover atividade",
    MODAL_REMOVER_ATIVIDADE_TEXTO: "Confirma a remoção desta atividade e todos os conhecimentos associados?",
    MODAL_REMOVER_CONHECIMENTO_TITULO: "Remover conhecimento",
    MODAL_REMOVER_CONHECIMENTO_TEXTO: "Confirma a remoção deste conhecimento?",
    ERRO_ADICIONAR: "Não foi possível adicionar atividade.",
    ERRO_REMOVER: "Não foi possível remover o item.",
    ERRO_SALVAR_ATIVIDADE: "Falha ao salvar edição da atividade.",
    ERRO_ADICIONAR_CONHECIMENTO: "Falha ao adicionar conhecimento.",
    ERRO_ATUALIZAR_CONHECIMENTO: "Falha ao atualizar conhecimento.",
    SUCESSO_IMPORTACAO: "Atividades importadas",
    AVISO_IMPORTACAO_DUPLICATAS: "Uma ou mais atividades selecionadas já existem no cadastro e não foram importadas.",
    MODAL_DISPONIBILIZAR_TITULO: "Disponibilização do cadastro",
    MODAL_DISPONIBILIZAR_REVISAO_TITULO: "Disponibilização da revisão do cadastro",
    MODAL_DISPONIBILIZAR_TEXTO: "Confirma a finalização e a disponibilização do cadastro? Essa ação bloqueia a edição e habilita a análise do cadastro por unidades superiores.",
    MODAL_DISPONIBILIZAR_REVISAO_TEXTO: "Confirma a finalização da revisão e a disponibilização do cadastro? Essa ação bloqueia a edição e habilita a análise do cadastro por unidades superiores.",
    BOTAO_HISTORICO_ANALISE: "Histórico de análise",
    MODAL_HISTORICO_TITULO: "Histórico de análise",
    MODAL_VALIDAR_TITULO: "Validação do cadastro",
    MODAL_ACEITE_REVISAO_TITULO: "Aceite da revisão do cadastro",
    MODAL_HOMOLOGAR_TITULO: "Homologação do cadastro",
    MODAL_VALIDAR_TEXTO: "Confirma o aceite do cadastro de atividades?",
    MODAL_ACEITE_REVISAO_TEXTO: "Confirma o aceite da revisão do cadastro de atividades?",
    MODAL_HOMOLOGAR_TEXTO: "Confirma a homologação do cadastro?",
    MODAL_DEVOLVER_TITULO: "Devolução do cadastro",
    MODAL_DEVOLVER_REVISAO_TITULO: "Devolução da revisão do cadastro",
    MODAL_DEVOLVER_TEXTO: "Confirma a devolução do cadastro para ajustes?",
    MODAL_DEVOLVER_REVISAO_TEXTO: "Confirma a devolução da revisão do cadastro para ajustes?",
    ERRO_DEVOLUCAO_JUSTIFICATIVA: "A justificativa é obrigatória para a devolução.",
    MODAL_IMPORTAR_TITULO: "Importação de atividades",
    BOTAO_DEVOLVER: "Devolver para ajustes",
    BOTAO_HOMOLOGAR: "Homologar",
    BOTAO_ACEITAR: "Registrar aceite",
    importacao: {
      NENHUM_PROCESSO: "Nenhum processo disponível para importação.",
      NENHUMA_ATIVIDADE: "Nenhuma atividade encontrada para esta unidade/processo.",
      SELECIONE_ATIVIDADE: "Selecione ao menos uma atividade para importar."
    }
  },
  unidade: {
    CARREGANDO: "Carregando unidade...",
    BOTAO_MAPA_VIGENTE: "Mapa vigente",
    BOTAO_CRIAR_ATRIBUICAO: "Criar atribuição",
    LABEL_TITULAR: "Titular:",
    LABEL_RESPONSAVEL: "Responsável:",
    LABEL_RAMAL: "Ramal:",
    LABEL_EMAIL: "E-mail:",
    NAO_INFORMADO: "Não informado",
    SUBORDINADAS_TITULO: "Unidades subordinadas",
    CAMPO_UNIDADE: "Unidade",
    EMPTY_TITLE: "Unidade não encontrada",
    EMPTY_DESCRIPTION: "Não foi possível localizar os dados da unidade solicitada.",
    ERRO_CARREGAR: "Erro ao carregar unidade",
  },
  sucesso: {
    ACEITE_REGISTRADO: "Aceite registrado",
    ACAO_EM_BLOCO_REALIZADA: "Ação em bloco realizada",
    ACEITES_REGISTRADOS_EM_BLOCO: "Aceites registrados em bloco",
    CADASTRO_ATIVIDADES_DISPONIBILIZADO: "Cadastro de atividades disponibilizado",
    CADASTROS_ACEITOS_EM_BLOCO: "Cadastros aceitos em bloco",
    CADASTROS_HOMOLOGADOS_EM_BLOCO: "Cadastros homologados em bloco",
    DEVOLUCAO_REALIZADA: "Devolução realizada",
    HOMOLOGACAO_EFETIVADA: "Homologação efetivada",
    HOMOLOGACOES_REGISTRADAS_EM_BLOCO: "Homologações registradas em bloco",
    MAPA_DISPONIBILIZADO: "Mapa de competências disponibilizado",
    MAPA_SUBMETIDO_COM_SUGESTOES: "Mapa submetido com sugestões para análise da unidade superior",
    MAPA_VALIDADO_SUBMETIDO: "Mapa validado e submetido para análise à unidade superior",
    MAPAS_ACEITOS_EM_BLOCO: "Mapas aceitos em bloco",
    MAPAS_DISPONIBILIZADOS_EM_BLOCO: "Mapas de competências disponibilizados em bloco",
    MAPAS_HOMOLOGADOS_EM_BLOCO: "Mapas de competências homologados em bloco",
    PROCESSO_ALTERADO: "Processo alterado.",
    PROCESSO_CRIADO: "Processo criado.",
    PROCESSO_FINALIZADO: "Processo finalizado",
    PROCESSO_INICIADO: "Processo iniciado",
    PROCESSO_REMOVIDO: (descricao: string) => `Processo ${descricao} removido`,
    REVISAO_CADASTRO_ATIVIDADES_DISPONIBILIZADA: "Revisão do cadastro de atividades disponibilizada",
  },
  alerta: {
    SUCESSO_REVISAO_DISPONIBILIZADA: (unidade: string) => `Revisão do cadastro da unidade ${unidade} disponibilizada para análise`,
    REVISAO_DEVOLVIDA: (unidade: string) => `Revisão do cadastro da unidade ${unidade} devolvida para ajustes`,
  },
  movimentacao: {
    CADASTRO_DISPONIBILIZADO: "Disponibilização do cadastro de atividades",
    REVISAO_CADASTRO_DISPONIBILIZADA: "Disponibilização da revisão do cadastro de atividades",
    REVISAO_CADASTRO_DEVOLVIDA: "Devolução da revisão do cadastro para ajustes",
    PROCESSO_INICIADO: "Processo iniciado",
    MAPA_VALIDADO: "Validação do mapa de competências",
    MAPA_VALIDACAO_ACEITA: "Mapa de competências validado",
    LEMBRETE_ENVIADO: "Lembrete de prazo enviado",
  },
  processo: {
    CONCLUIDO: "Processo concluído.",
    FINALIZAR: "Finalizar",
    CARREGANDO_DETALHES: "Carregando detalhes do processo...",
    ERRO_PADRAO: "Ocorreu um erro",
    FINALIZACAO_TITULO: "Finalização de processo",
    FINALIZACAO_CONFIRMACAO_PREFIXO: "Confirma a finalização do processo",
    FINALIZACAO_CONFIRMACAO_COMPLEMENTO:
      "Essa ação tornará vigentes os mapas de competências homologados e notificará todas as unidades participantes do processo.",
    ERRO_ACAO_BLOCO: "Erro ao executar ação em bloco",
    INFO_TIPO: "Tipo",
    INFO_SITUACAO: "Situação",
    INFO_DATA_LIMITE: "Data limite",
    INFO_UNIDADES: "Unidades participantes",
    cadastro: {
      TITULO: "Cadastro de processo",
      BOTAO_INICIAR: "Iniciar",
      BOTAO_SALVAR: "Salvar",
      BOTAO_REMOVER: "Remover",
      BOTAO_CANCELAR: "Cancelar",
      INICIAR_TITULO: "Iniciar processo",
      INICIAR_CONFIRMACAO: "Ao iniciar o processo, não será mais possível editá-lo ou removê-lo e todas as unidades participantes serão notificadas por e-mail.",
      REMOVER_TITULO: "Remover processo",
      REMOVER_CONFIRMACAO: (desc: string) => `Remover o processo '${desc}'? Esta ação não poderá ser desfeita.`,
      ERRO_CARREGAR_DETALHES: "Não foi possível carregar os detalhes do processo.",
      ERRO_CRIAR_PARA_INICIAR: "Não foi possível criar o processo para iniciá-lo.",
      ERRO_INICIAR_PROCESSO: "Não foi possível iniciar o processo. Tente novamente.",
      ERRO_REMOVER_PROCESSO: "Não foi possível remover o processo. Tente novamente.",
    },
  },
  acaoBloco: {
    aceitar: {
      ROTULO_CADASTRO: "Aceitar cadastro em bloco",
      ROTULO_VALIDACAO: "Aceitar mapas em bloco",
      ROTULO_MISTO: "Registrar aceite em bloco",
      TITULO_CADASTRO: "Aceite de cadastro em bloco",
      TITULO_VALIDACAO: "Aceite de mapas em bloco",
      TITULO_MISTO: "Aceite em bloco",
      TEXTO_CADASTRO: "Selecione as unidades cujos cadastros deverão ser aceitos:",
      TEXTO_VALIDACAO: "Selecione as unidades para aceite dos mapas correspondentes",
      TEXTO_MISTO: "Selecione as unidades para registrar o aceite correspondente.",
      BOTAO: "Registrar aceite",
    },
    homologar: {
      ROTULO_CADASTRO: "Homologar em bloco",
      ROTULO_VALIDACAO: "Homologar mapas em bloco",
      ROTULO_MISTO: "Homologar em bloco",
      TITULO_CADASTRO: "Homologação de cadastro em bloco",
      TITULO_VALIDACAO: "Homologação de mapa em bloco",
      TITULO_MISTO: "Homologação em bloco",
      TEXTO_CADASTRO: "Selecione abaixo as unidades cujos cadastros deverão ser homologados:",
      TEXTO_VALIDACAO: "Selecione abaixo as unidades cujos mapas deverão ser homologados:",
      TEXTO_MISTO: "Selecione as unidades para homologação em bloco.",
      BOTAO: "Homologar",
    },
    disponibilizar: {
      ROTULO: "Disponibilizar em bloco",
      TITULO: "Disponibilização de mapa em bloco",
      TEXTO: "Selecione as unidades cujos mapas deverão ser disponibilizados:",
      BOTAO: "Disponibilizar",
    },
  },
  configuracoes: {
    TITULO: "Configurações",
    LABEL_DIAS_INATIVACAO: "Dias para inativação de processos",
    DESC_DIAS_INATIVACAO: "Dias depois da finalização de um processo para que seja considerado inativo.",
    LABEL_DIAS_ALERTA_NOVO: "Dias para indicação de alerta como novo",
    DESC_DIAS_ALERTA_NOVO: "Dias depois de um alerta ser enviado para que deixe de ser marcado como novo.",
    SUCESSO_SALVAR: "Configurações salvas.",
    ERRO_SALVAR: "Erro ao salvar configurações.",
    BOTAO_SALVAR: "Salvar configurações",
  },
} as const;
