export const TEXTOS_MOVIMENTACAO = {
    CADASTRO_DISPONIBILIZADO: "Cadastro disponibilizado",
    REVISAO_CADASTRO_DISPONIBILIZADA: "Revisão do cadastro disponibilizada",
    REVISAO_CADASTRO_DEVOLVIDA: "Revisão do cadastro devolvida para ajustes",
    PROCESSO_INICIADO: "Processo iniciado",
    MAPA_VALIDACAO_ACEITA: "Validação do mapa aceita",
} as const;

export const TEXTOS_SUBPROCESSO = {
    BOTAO_ALTERAR_DATA_LIMITE: "Alterar data limite",
    BOTAO_REABRIR_CADASTRO: "Reabrir cadastro",
    BOTAO_REABRIR_REVISAO: "Reabrir revisão",
    BOTAO_ENVIAR_LEMBRETE: "Enviar lembrete",
    LABEL_PROCESSO: "Processo",
    LABEL_SITUACAO: "Situação",
    LABEL_LOCALIZACAO: "Localização atual",
    LABEL_PRAZO_ETAPA: "Prazo para conclusão da etapa atual",
    LABEL_TITULAR: "Titular",
    LABEL_RESPONSAVEL: "Responsável",
    MOVIMENTACOES_TITULO: "Movimentações",
    MOVIMENTACOES_VAZIO_TITULO: "Sem movimentações ainda",
    MOVIMENTACOES_VAZIO_TEXTO: "O histórico deste processo aparece aqui assim que houver atividade.",
    MOVIMENTACOES_CAMPO_DATA: "Data/hora",
    MOVIMENTACOES_CAMPO_ORIGEM: "Origem",
    MOVIMENTACOES_CAMPO_DESTINO: "Destino",
    MOVIMENTACOES_CAMPO_DESCRICAO: "Descrição",
    ERRO_SEM_PERMISSAO_DATA: "Você não tem permissão para alterar a data limite.",
    SUCESSO_DATA_ALTERADA: "Data limite alterada",
    ERRO_DATA_ALTERADA: "Não foi possível alterar a data limite",
    SUCESSO_CADASTRO_REABERTO: "Cadastro reaberto",
    SUCESSO_REVISAO_REABERTA: "Revisão reaberta",
    SUCESSO_LEMBRETE_ENVIADO: "Lembrete enviado",
    ERRO_LEMBRETE_ENVIADO: "Não foi possível enviar o lembrete",
    CARREGANDO: "Carregando informações da unidade...",
    NAO_ENCONTRADO_TITULO: "Falha grave ao localizar subprocesso",
    NAO_ENCONTRADO_DESC: "A ausência deste subprocesso é inconsistente. A operação foi bloqueada para segurança e deve ser auditada.",
    REABRIR_CADASTRO_TITULO: "Reabrir cadastro",
    REABRIR_REVISAO_TITULO: "Reabrir revisão",
    REABRIR_JUSTIFICATIVA_PREFIXO: "Informe a justificativa para reabrir o",
    REABRIR_JUSTIFICATIVA_PLACEHOLDER: "",
    CADASTRO: "cadastro",
    REVISAO_CADASTRO: "revisão de cadastro",
    LEMBRETE_TITULO: "Enviar lembrete",
    BOTAO_CONFIRMAR_LEMBRETE: "Enviar",
    LEMBRETE_MODELO_PREFIXO: (sigla: string) => `Confirma envio de lembrete para a unidade ${sigla}?`,
    DETALHE_UNIDADES_TITULO: "Unidades participantes",
    COLUNA_UNIDADE: "Unidade",
    COLUNA_SITUACAO: "Situação",
    COLUNA_DATA_LIMITE: "Data limite",
    cards: {
        ATUALIZACAO_CADASTRO_TITULO: "Atividades e conhecimentos",
        ATUALIZACAO_CADASTRO_TEXTO: "Cadastro de atividades e conhecimentos da unidade",
        MAPA_TITULO: "Mapa de competências",
        MAPA_TEXTO: "Mapa de competências técnicas da unidade",
        AUTOAVALIACAO_TITULO: "Autoavaliação",
        AUTOAVALIACAO_TEXTO: "Realize sua autoavaliação de competências",
        OCUPACOES_TITULO: "Situação de capacitação",
        OCUPACOES_TEXTO: "Preenchimento da situação de capacitação dos servidores da unidade",
        MONITORAMENTO_TITULO: "Monitoramento",
        MONITORAMENTO_TEXTO: "Acompanhamento e conclusão do diagnóstico da unidade",
    },
} as const;

export const TEXTOS_SUCESSO_SUBPROCESSO = {
    ACEITE_REGISTRADO: "Aceite registrado",
    DEVOLUCAO_REALIZADA: "Devolução realizada",
    HOMOLOGACAO_EFETIVADA: "Homologação efetivada",
} as const;
