package sgc.alerta.modelo;

public enum TipoAlerta {
    PROCESSO_INICIADO_OPERACIONAL,
    PROCESSO_INICIADO_INTERMEDIARIA,
    PROCESSO_INICIADO_INTEROPERACIONAL_OP,
    PROCESSO_INICIADO_INTEROPERACIONAL_INT,
    CADASTRO_DISPONIBILIZADO,
    CADASTRO_DEVOLVIDO
}
