export {
    preencherFormularioLogin,
    selecionarPerfil,
    fecharAlerta,
    cancelarNoModal as cancelarNoModalLogin,
    confirmarNoModal as confirmarNoModalLogin,
} from './acoes-login';
export * from './acoes-atividades';
export {
    selecionarUnidadesPorId,
    selecionarUnidadesPorSigla,
    preencherFormularioProcesso,
    selecionarPrimeiraUnidade,
    clicarPrimeiroProcessoTabela,
    criarProcessoCompleto,
    tentarSalvarProcessoVazio,
    criarProcessoSemUnidades,
    navegarParaProcessoNaTabela,
    editarDescricaoProcesso,
    criarProcessoMapeamentoCompleto,
    clicarBotaoFinalizarProcesso,
    abrirModalFinalizacaoProcesso,
    confirmarFinalizacaoNoModal,
    finalizarProcesso,
    disponibilizarCadastro,
    abrirModalDevolucao,
    devolverParaAjustes,
    devolverCadastro,
    aceitarCadastro,
    registrarAceiteRevisao,
    homologarCadastro,
    clicarBotaoIniciarProcesso,
    clicarProcessoNaTabela,
    iniciarProcesso,
    removerProcessoComConfirmacao,
    cancelarRemocaoProcesso,
    confirmarInicializacaoProcesso,
    removerProcessoConfirmandoNoModal,
    clicarUnidadeNaTabelaDetalhes,
    clicarBotaoHistoricoAnalise,
    homologarRevisaoCadastro,
    iniciarProcessoMapeamento,
    confirmarIniciacaoProcesso,
    cancelarIniciacaoProcesso,
    criarProcessoBasico,
    abrirProcessoPorNome
} from './acoes-processo';
export * from './acoes-mapa';
export {
    cancelarNoModal,
    confirmarNoModal,
    confirmarRemocaoNoModal,
    abrirDialogoRemocaoProcesso,
    clicarIniciarProcesso,
    abrirModalInicializacaoProcesso,
    confirmarInicializacaoNoModal,
    cancelarModal,
    clicarBotaoHistoricoAnalise as clicarBotaoHistoricoAnaliseModal,
} from './acoes-modais';
export * from './acoes-validacao';
