package sgc.subprocesso.model;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.assertj.core.api.Assertions.assertThat;
import static sgc.subprocesso.model.SituacaoSubprocesso.*;
import sgc.processo.model.TipoProcesso;

@DisplayName("SituacaoSubprocesso - Teste de Transições")
class SituacaoSubprocessoTest {

    @ParameterizedTest(name = "De {0} para {1} (Tipo {3}) deve ser {2}")
    @CsvSource({
        "NAO_INICIADO, MAPEAMENTO_CADASTRO_EM_ANDAMENTO, true, MAPEAMENTO",
        "NAO_INICIADO, REVISAO_CADASTRO_EM_ANDAMENTO, true, REVISAO",
        "NAO_INICIADO, DIAGNOSTICO_AUTOAVALIACAO_EM_ANDAMENTO, true, DIAGNOSTICO",
        "NAO_INICIADO, MAPEAMENTO_CADASTRO_EM_ANDAMENTO, false, REVISAO",
        "NAO_INICIADO, REVISAO_CADASTRO_EM_ANDAMENTO, false, MAPEAMENTO",
        "NAO_INICIADO, DIAGNOSTICO_AUTOAVALIACAO_EM_ANDAMENTO, false, MAPEAMENTO",
        "NAO_INICIADO, NAO_INICIADO, true, MAPEAMENTO",
        
        // --- MAPEAMENTO ---
        "MAPEAMENTO_CADASTRO_EM_ANDAMENTO, MAPEAMENTO_CADASTRO_DISPONIBILIZADO, true, MAPEAMENTO",
        "MAPEAMENTO_CADASTRO_DISPONIBILIZADO, MAPEAMENTO_CADASTRO_EM_ANDAMENTO, true, MAPEAMENTO",
        "MAPEAMENTO_CADASTRO_DISPONIBILIZADO, MAPEAMENTO_CADASTRO_HOMOLOGADO, true, MAPEAMENTO",
        "MAPEAMENTO_CADASTRO_HOMOLOGADO, MAPEAMENTO_MAPA_CRIADO, true, MAPEAMENTO",
        "MAPEAMENTO_CADASTRO_HOMOLOGADO, MAPEAMENTO_MAPA_DISPONIBILIZADO, true, MAPEAMENTO",
        "MAPEAMENTO_CADASTRO_HOMOLOGADO, MAPEAMENTO_CADASTRO_EM_ANDAMENTO, true, MAPEAMENTO",
        "MAPEAMENTO_MAPA_CRIADO, MAPEAMENTO_MAPA_DISPONIBILIZADO, true, MAPEAMENTO",
        "MAPEAMENTO_MAPA_CRIADO, MAPEAMENTO_CADASTRO_HOMOLOGADO, true, MAPEAMENTO",
        "MAPEAMENTO_MAPA_DISPONIBILIZADO, MAPEAMENTO_MAPA_COM_SUGESTOES, true, MAPEAMENTO",
        "MAPEAMENTO_MAPA_DISPONIBILIZADO, MAPEAMENTO_MAPA_VALIDADO, true, MAPEAMENTO",
        "MAPEAMENTO_MAPA_DISPONIBILIZADO, MAPEAMENTO_MAPA_CRIADO, true, MAPEAMENTO",
        "MAPEAMENTO_MAPA_COM_SUGESTOES, MAPEAMENTO_MAPA_DISPONIBILIZADO, true, MAPEAMENTO",
        "MAPEAMENTO_MAPA_COM_SUGESTOES, MAPEAMENTO_MAPA_CRIADO, true, MAPEAMENTO",
        "MAPEAMENTO_MAPA_VALIDADO, MAPEAMENTO_MAPA_HOMOLOGADO, true, MAPEAMENTO",
        "MAPEAMENTO_MAPA_VALIDADO, MAPEAMENTO_MAPA_DISPONIBILIZADO, true, MAPEAMENTO",
        "MAPEAMENTO_MAPA_HOMOLOGADO, MAPEAMENTO_MAPA_VALIDADO, false, MAPEAMENTO",

        // --- REVISAO ---
        "REVISAO_CADASTRO_EM_ANDAMENTO, REVISAO_CADASTRO_DISPONIBILIZADA, true, REVISAO",
        "REVISAO_CADASTRO_DISPONIBILIZADA, REVISAO_CADASTRO_EM_ANDAMENTO, true, REVISAO",
        "REVISAO_CADASTRO_DISPONIBILIZADA, REVISAO_CADASTRO_HOMOLOGADA, true, REVISAO",
        "REVISAO_CADASTRO_DISPONIBILIZADA, REVISAO_MAPA_HOMOLOGADO, true, REVISAO",
        "REVISAO_CADASTRO_HOMOLOGADA, REVISAO_MAPA_AJUSTADO, true, REVISAO",
        "REVISAO_CADASTRO_HOMOLOGADA, REVISAO_MAPA_DISPONIBILIZADO, true, REVISAO",
        "REVISAO_CADASTRO_HOMOLOGADA, REVISAO_CADASTRO_EM_ANDAMENTO, true, REVISAO",
        "REVISAO_MAPA_AJUSTADO, REVISAO_MAPA_DISPONIBILIZADO, true, REVISAO",
        "REVISAO_MAPA_AJUSTADO, REVISAO_CADASTRO_HOMOLOGADA, true, REVISAO",
        "REVISAO_MAPA_DISPONIBILIZADO, REVISAO_MAPA_COM_SUGESTOES, true, REVISAO",
        "REVISAO_MAPA_DISPONIBILIZADO, REVISAO_MAPA_VALIDADO, true, REVISAO",
        "REVISAO_MAPA_DISPONIBILIZADO, REVISAO_MAPA_AJUSTADO, true, REVISAO",
        "REVISAO_MAPA_COM_SUGESTOES, REVISAO_MAPA_DISPONIBILIZADO, true, REVISAO",
        "REVISAO_MAPA_COM_SUGESTOES, REVISAO_MAPA_AJUSTADO, true, REVISAO",
        "REVISAO_MAPA_VALIDADO, REVISAO_MAPA_HOMOLOGADO, true, REVISAO",
        "REVISAO_MAPA_VALIDADO, REVISAO_MAPA_DISPONIBILIZADO, true, REVISAO",
        "REVISAO_MAPA_HOMOLOGADO, REVISAO_MAPA_VALIDADO, false, REVISAO",

        // --- DIAGNOSTICO ---
        "DIAGNOSTICO_AUTOAVALIACAO_EM_ANDAMENTO, DIAGNOSTICO_MONITORAMENTO, true, DIAGNOSTICO",
        "DIAGNOSTICO_MONITORAMENTO, DIAGNOSTICO_CONCLUIDO, true, DIAGNOSTICO",
        "DIAGNOSTICO_CONCLUIDO, DIAGNOSTICO_MONITORAMENTO, false, DIAGNOSTICO",

        // Transições Inválidas (Misturando tipos)
        "MAPEAMENTO_CADASTRO_EM_ANDAMENTO, REVISAO_CADASTRO_EM_ANDAMENTO, false, MAPEAMENTO",
        "REVISAO_CADASTRO_EM_ANDAMENTO, MAPEAMENTO_CADASTRO_EM_ANDAMENTO, false, REVISAO",
        "DIAGNOSTICO_AUTOAVALIACAO_EM_ANDAMENTO, MAPEAMENTO_CADASTRO_EM_ANDAMENTO, false, DIAGNOSTICO",
        "NAO_INICIADO, MAPEAMENTO_MAPA_HOMOLOGADO, false, MAPEAMENTO",
        "MAPEAMENTO_CADASTRO_EM_ANDAMENTO, MAPEAMENTO_MAPA_CRIADO, false, MAPEAMENTO",
        "MAPEAMENTO_MAPA_HOMOLOGADO, MAPEAMENTO_CADASTRO_EM_ANDAMENTO, false, MAPEAMENTO"
    })
    void testTransicoes(SituacaoSubprocesso de, SituacaoSubprocesso para, boolean esperado, TipoProcesso tipo) {
        assertThat(de.podeTransicionarPara(para, tipo)).isEqualTo(esperado);
    }

    @Test
    @DisplayName("Deve permitir transição para si mesmo")
    void testMesmaSituacao() {
        assertThat(NAO_INICIADO.podeTransicionarPara(NAO_INICIADO, TipoProcesso.MAPEAMENTO)).isTrue();
    }

    @Test
    @DisplayName("Deve testar ramos da verificação de prefixo (MAPEAMENTO)")
    void testRamosPrefixoMapeamento() {
        // this != NAO_INICIADO && nova != NAO_INICIADO
        // this.name().startsWith("MAPEAMENTO") && !nova.name().startsWith("MAPEAMENTO") -> false
        assertThat(MAPEAMENTO_CADASTRO_EM_ANDAMENTO.podeTransicionarPara(REVISAO_CADASTRO_EM_ANDAMENTO, TipoProcesso.MAPEAMENTO)).isFalse();
        
        // this.name().startsWith("MAPEAMENTO") && nova.name().startsWith("MAPEAMENTO") -> prossegue para switch
        assertThat(MAPEAMENTO_CADASTRO_EM_ANDAMENTO.podeTransicionarPara(MAPEAMENTO_CADASTRO_DISPONIBILIZADO, TipoProcesso.MAPEAMENTO)).isTrue();
    }

    @Test
    @DisplayName("Deve testar ramos da verificação de prefixo (REVISAO)")
    void testRamosPrefixoRevisao() {
        assertThat(REVISAO_CADASTRO_EM_ANDAMENTO.podeTransicionarPara(MAPEAMENTO_CADASTRO_EM_ANDAMENTO, TipoProcesso.REVISAO)).isFalse();
        assertThat(REVISAO_CADASTRO_EM_ANDAMENTO.podeTransicionarPara(REVISAO_CADASTRO_DISPONIBILIZADA, TipoProcesso.REVISAO)).isTrue();
    }

    @Test
    @DisplayName("Deve testar ramos da verificação de prefixo (DIAGNOSTICO)")
    void testRamosPrefixoDiagnostico() {
        assertThat(DIAGNOSTICO_AUTOAVALIACAO_EM_ANDAMENTO.podeTransicionarPara(MAPEAMENTO_CADASTRO_EM_ANDAMENTO, TipoProcesso.DIAGNOSTICO)).isFalse();
        assertThat(DIAGNOSTICO_AUTOAVALIACAO_EM_ANDAMENTO.podeTransicionarPara(DIAGNOSTICO_MONITORAMENTO, TipoProcesso.DIAGNOSTICO)).isTrue();
    }
}
