package sgc.subprocesso.model;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import sgc.processo.model.TipoProcesso;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static sgc.subprocesso.model.SituacaoSubprocesso.*;

class SituacaoSubprocessoCoverageTest {

    @Test
    @DisplayName("Mesma situação deve retornar true")
    void mesmaSituacao() {
        assertTrue(MAPEAMENTO_CADASTRO_EM_ANDAMENTO.podeTransicionarPara(MAPEAMENTO_CADASTRO_EM_ANDAMENTO, TipoProcesso.MAPEAMENTO));
    }

    @Test
    @DisplayName("Mistura de tipos deve retornar false")
    void misturaTipos() {
        assertFalse(MAPEAMENTO_CADASTRO_EM_ANDAMENTO.podeTransicionarPara(REVISAO_CADASTRO_EM_ANDAMENTO, TipoProcesso.MAPEAMENTO));
        assertFalse(REVISAO_CADASTRO_EM_ANDAMENTO.podeTransicionarPara(MAPEAMENTO_CADASTRO_EM_ANDAMENTO, TipoProcesso.REVISAO));
        assertFalse(DIAGNOSTICO_AUTOAVALIACAO_EM_ANDAMENTO.podeTransicionarPara(MAPEAMENTO_CADASTRO_EM_ANDAMENTO, TipoProcesso.DIAGNOSTICO));
        assertFalse(MAPEAMENTO_CADASTRO_EM_ANDAMENTO.podeTransicionarPara(DIAGNOSTICO_AUTOAVALIACAO_EM_ANDAMENTO, TipoProcesso.MAPEAMENTO));
    }

    @ParameterizedTest
    @CsvSource({
            // NAO_INICIADO
            "NAO_INICIADO, MAPEAMENTO_CADASTRO_EM_ANDAMENTO, MAPEAMENTO, true",
            "NAO_INICIADO, REVISAO_CADASTRO_EM_ANDAMENTO, REVISAO, true",
            "NAO_INICIADO, DIAGNOSTICO_AUTOAVALIACAO_EM_ANDAMENTO, DIAGNOSTICO, true",
            "NAO_INICIADO, MAPEAMENTO_CADASTRO_HOMOLOGADO, MAPEAMENTO, false",

            // MAPEAMENTO
            "MAPEAMENTO_CADASTRO_EM_ANDAMENTO, MAPEAMENTO_CADASTRO_DISPONIBILIZADO, MAPEAMENTO, true",
            "MAPEAMENTO_CADASTRO_EM_ANDAMENTO, MAPEAMENTO_CADASTRO_HOMOLOGADO, MAPEAMENTO, false",

            "MAPEAMENTO_CADASTRO_DISPONIBILIZADO, MAPEAMENTO_CADASTRO_EM_ANDAMENTO, MAPEAMENTO, true",
            "MAPEAMENTO_CADASTRO_DISPONIBILIZADO, MAPEAMENTO_CADASTRO_HOMOLOGADO, MAPEAMENTO, true",
            "MAPEAMENTO_CADASTRO_DISPONIBILIZADO, MAPEAMENTO_MAPA_CRIADO, MAPEAMENTO, false",

            "MAPEAMENTO_CADASTRO_HOMOLOGADO, MAPEAMENTO_MAPA_CRIADO, MAPEAMENTO, true",
            "MAPEAMENTO_CADASTRO_HOMOLOGADO, MAPEAMENTO_MAPA_DISPONIBILIZADO, MAPEAMENTO, true",
            "MAPEAMENTO_CADASTRO_HOMOLOGADO, MAPEAMENTO_CADASTRO_EM_ANDAMENTO, MAPEAMENTO, true",
            "MAPEAMENTO_CADASTRO_HOMOLOGADO, MAPEAMENTO_MAPA_VALIDADO, MAPEAMENTO, false",

            "MAPEAMENTO_MAPA_CRIADO, MAPEAMENTO_MAPA_DISPONIBILIZADO, MAPEAMENTO, true",
            "MAPEAMENTO_MAPA_CRIADO, MAPEAMENTO_CADASTRO_HOMOLOGADO, MAPEAMENTO, true",
            "MAPEAMENTO_MAPA_CRIADO, MAPEAMENTO_MAPA_VALIDADO, MAPEAMENTO, false",

            "MAPEAMENTO_MAPA_DISPONIBILIZADO, MAPEAMENTO_MAPA_COM_SUGESTOES, MAPEAMENTO, true",
            "MAPEAMENTO_MAPA_DISPONIBILIZADO, MAPEAMENTO_MAPA_VALIDADO, MAPEAMENTO, true",
            "MAPEAMENTO_MAPA_DISPONIBILIZADO, MAPEAMENTO_MAPA_CRIADO, MAPEAMENTO, true",
            "MAPEAMENTO_MAPA_DISPONIBILIZADO, MAPEAMENTO_MAPA_HOMOLOGADO, MAPEAMENTO, false",

            "MAPEAMENTO_MAPA_COM_SUGESTOES, MAPEAMENTO_MAPA_DISPONIBILIZADO, MAPEAMENTO, true",
            "MAPEAMENTO_MAPA_COM_SUGESTOES, MAPEAMENTO_MAPA_CRIADO, MAPEAMENTO, true",
            "MAPEAMENTO_MAPA_COM_SUGESTOES, MAPEAMENTO_MAPA_VALIDADO, MAPEAMENTO, false",

            "MAPEAMENTO_MAPA_VALIDADO, MAPEAMENTO_MAPA_HOMOLOGADO, MAPEAMENTO, true",
            "MAPEAMENTO_MAPA_VALIDADO, MAPEAMENTO_MAPA_DISPONIBILIZADO, MAPEAMENTO, true",
            "MAPEAMENTO_MAPA_VALIDADO, MAPEAMENTO_MAPA_CRIADO, MAPEAMENTO, false",

            "MAPEAMENTO_MAPA_HOMOLOGADO, MAPEAMENTO_CADASTRO_EM_ANDAMENTO, MAPEAMENTO, false",

            // REVISAO
            "REVISAO_CADASTRO_EM_ANDAMENTO, REVISAO_CADASTRO_DISPONIBILIZADA, REVISAO, true",
            "REVISAO_CADASTRO_EM_ANDAMENTO, REVISAO_CADASTRO_HOMOLOGADA, REVISAO, false",

            "REVISAO_CADASTRO_DISPONIBILIZADA, REVISAO_CADASTRO_EM_ANDAMENTO, REVISAO, true",
            "REVISAO_CADASTRO_DISPONIBILIZADA, REVISAO_CADASTRO_HOMOLOGADA, REVISAO, true",
            "REVISAO_CADASTRO_DISPONIBILIZADA, REVISAO_MAPA_HOMOLOGADO, REVISAO, true",
            "REVISAO_CADASTRO_DISPONIBILIZADA, REVISAO_MAPA_AJUSTADO, REVISAO, false",

            "REVISAO_CADASTRO_HOMOLOGADA, REVISAO_MAPA_AJUSTADO, REVISAO, true",
            "REVISAO_CADASTRO_HOMOLOGADA, REVISAO_MAPA_DISPONIBILIZADO, REVISAO, true",
            "REVISAO_CADASTRO_HOMOLOGADA, REVISAO_CADASTRO_EM_ANDAMENTO, REVISAO, true",
            "REVISAO_CADASTRO_HOMOLOGADA, REVISAO_MAPA_VALIDADO, REVISAO, false",

            "REVISAO_MAPA_AJUSTADO, REVISAO_MAPA_DISPONIBILIZADO, REVISAO, true",
            "REVISAO_MAPA_AJUSTADO, REVISAO_CADASTRO_HOMOLOGADA, REVISAO, true",
            "REVISAO_MAPA_AJUSTADO, REVISAO_MAPA_VALIDADO, REVISAO, false",

            "REVISAO_MAPA_DISPONIBILIZADO, REVISAO_MAPA_COM_SUGESTOES, REVISAO, true",
            "REVISAO_MAPA_DISPONIBILIZADO, REVISAO_MAPA_VALIDADO, REVISAO, true",
            "REVISAO_MAPA_DISPONIBILIZADO, REVISAO_MAPA_AJUSTADO, REVISAO, true",
            "REVISAO_MAPA_DISPONIBILIZADO, REVISAO_MAPA_HOMOLOGADO, REVISAO, false",

            "REVISAO_MAPA_COM_SUGESTOES, REVISAO_MAPA_DISPONIBILIZADO, REVISAO, true",
            "REVISAO_MAPA_COM_SUGESTOES, REVISAO_MAPA_AJUSTADO, REVISAO, true",
            "REVISAO_MAPA_COM_SUGESTOES, REVISAO_MAPA_VALIDADO, REVISAO, false",

            "REVISAO_MAPA_VALIDADO, REVISAO_MAPA_HOMOLOGADO, REVISAO, true",
            "REVISAO_MAPA_VALIDADO, REVISAO_MAPA_DISPONIBILIZADO, REVISAO, true",
            "REVISAO_MAPA_VALIDADO, REVISAO_MAPA_AJUSTADO, REVISAO, false",

            "REVISAO_MAPA_HOMOLOGADO, REVISAO_CADASTRO_EM_ANDAMENTO, REVISAO, false",
            
            // DIAGNOSTICO
            "DIAGNOSTICO_AUTOAVALIACAO_EM_ANDAMENTO, DIAGNOSTICO_MONITORAMENTO, DIAGNOSTICO, true",
            "DIAGNOSTICO_AUTOAVALIACAO_EM_ANDAMENTO, DIAGNOSTICO_CONCLUIDO, DIAGNOSTICO, false",
            
            "DIAGNOSTICO_MONITORAMENTO, DIAGNOSTICO_CONCLUIDO, DIAGNOSTICO, true",
            "DIAGNOSTICO_MONITORAMENTO, DIAGNOSTICO_AUTOAVALIACAO_EM_ANDAMENTO, DIAGNOSTICO, false",
            
            "DIAGNOSTICO_CONCLUIDO, DIAGNOSTICO_MONITORAMENTO, DIAGNOSTICO, false"
    })
    @DisplayName("Transições")
    void transicoes(SituacaoSubprocesso origem, SituacaoSubprocesso destino, TipoProcesso tipo, boolean esperado) {
        if (esperado) {
            assertTrue(origem.podeTransicionarPara(destino, tipo), 
                () -> "Deveria permitir transição de " + origem + " para " + destino);
        } else {
            assertFalse(origem.podeTransicionarPara(destino, tipo), 
                () -> "Não deveria permitir transição de " + origem + " para " + destino);
        }
    }
}
