-- SCRIPT DDL: Módulo de Diagnóstico - SGC
-- Criado para conformidade com as regras do banco de dados relacional do SGC

-- Tabela: DIAGNOSTICO
-- Mapeia o diagnóstico global de uma determinada unidade participante
CREATE TABLE IF NOT EXISTS sgc.diagnostico
(
    codigo                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    subprocesso_codigo      BIGINT NOT NULL UNIQUE,
    situacao                VARCHAR(50) NOT NULL,
    data_conclusao          TIMESTAMP(6),
    justificativa_conclusao TEXT,
    CONSTRAINT pk_diagnostico PRIMARY KEY (codigo),
    CONSTRAINT fk_diagnostico_subprocesso FOREIGN KEY (subprocesso_codigo) REFERENCES sgc.subprocesso (codigo),
    CONSTRAINT ck_diagnostico_situacao CHECK (situacao IN ('EM_ANDAMENTO', 'CONCLUIDO', 'VALIDADO', 'HOMOLOGADO'))
);

-- Tabela: AVALIACAO_SERVIDOR
-- Registra a avaliação individual de cada servidor para cada competência do mapa da unidade
CREATE TABLE IF NOT EXISTS sgc.avaliacao_servidor
(
    codigo             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    diagnostico_codigo BIGINT NOT NULL,
    servidor_titulo    VARCHAR(255) NOT NULL,
    competencia_codigo BIGINT NOT NULL,
    importancia        VARCHAR(10),
    dominio            VARCHAR(10),
    gap                INT,
    observacoes        TEXT,
    situacao_servidor  VARCHAR(50) NOT NULL,
    CONSTRAINT pk_avaliacao_servidor PRIMARY KEY (codigo),
    CONSTRAINT fk_avaliacao_diagnostico FOREIGN KEY (diagnostico_codigo) REFERENCES sgc.diagnostico (codigo),
    CONSTRAINT fk_avaliacao_servidor FOREIGN KEY (servidor_titulo) REFERENCES sgc.vw_usuario (titulo),
    CONSTRAINT fk_avaliacao_competencia FOREIGN KEY (competencia_codigo) REFERENCES sgc.competencia (codigo),
    CONSTRAINT uk_avaliacao_servidor UNIQUE (diagnostico_codigo, servidor_titulo, competencia_codigo),
    CONSTRAINT ck_avaliacao_importancia CHECK (importancia IN ('NA', 'N1', 'N2', 'N3', 'N4', 'N5', 'N6')),
    CONSTRAINT ck_avaliacao_dominio CHECK (dominio IN ('NA', 'N1', 'N2', 'N3', 'N4', 'N5', 'N6')),
    CONSTRAINT ck_avaliacao_situacao CHECK (situacao_servidor IN ('AUTOAVALIACAO_NAO_REALIZADA', 'AUTOAVALIACAO_CONCLUIDA', 'CONSENSO_CRIADO', 'CONSENSO_APROVADO', 'AVALIACAO_IMPOSSIBILITADA'))
);

-- Tabela: OCUPACAO_CRITICA
-- Registra as ocupações críticas e situações de capacitação (matriz por servidor e competência)
CREATE TABLE IF NOT EXISTS sgc.ocupacao_critica
(
    codigo               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    diagnostico_codigo   BIGINT NOT NULL,
    servidor_titulo      VARCHAR(255) NOT NULL,
    competencia_codigo   BIGINT NOT NULL,
    situacao_capacitacao VARCHAR(10) NOT NULL,
    CONSTRAINT pk_ocupacao_critica PRIMARY KEY (codigo),
    CONSTRAINT fk_ocupacao_diagnostico FOREIGN KEY (diagnostico_codigo) REFERENCES sgc.diagnostico (codigo),
    CONSTRAINT fk_ocupacao_servidor FOREIGN KEY (servidor_titulo) REFERENCES sgc.vw_usuario (titulo),
    CONSTRAINT fk_ocupacao_competencia FOREIGN KEY (competencia_codigo) REFERENCES sgc.competencia (codigo),
    CONSTRAINT uk_ocupacao_critica UNIQUE (diagnostico_codigo, servidor_titulo, competencia_codigo),
    CONSTRAINT ck_ocupacao_situacao_capacitacao CHECK (situacao_capacitacao IN ('NA', 'AC', 'EC', 'C', 'I'))
);

-- Índices de performance para otimização de consultas e junções
CREATE INDEX IF NOT EXISTS idx_diagnostico_subprocesso ON sgc.diagnostico (subprocesso_codigo);
CREATE INDEX IF NOT EXISTS idx_avaliacao_diagnostico ON sgc.avaliacao_servidor (diagnostico_codigo);
CREATE INDEX IF NOT EXISTS idx_avaliacao_servidor ON sgc.avaliacao_servidor (servidor_titulo);
CREATE INDEX IF NOT EXISTS idx_avaliacao_competencia ON sgc.avaliacao_servidor (competencia_codigo);
CREATE INDEX IF NOT EXISTS idx_ocupacao_diagnostico ON sgc.ocupacao_critica (diagnostico_codigo);
CREATE INDEX IF NOT EXISTS idx_ocupacao_servidor ON sgc.ocupacao_critica (servidor_titulo);
CREATE INDEX IF NOT EXISTS idx_ocupacao_competencia ON sgc.ocupacao_critica (competencia_codigo);
