# Configurações otimizadas para testes E2E executados por agentes de IA (como Jules)
server:
  port: 10000
  shutdown: graceful
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  sql:
    init:
      mode: never
  devtools:
    restart:
      enabled: false
