create table if not exists sgc.administrador
(
    usuario_titulo varchar(255) not null,
    primary key (usuario_titulo)
);

create table if not exists sgc.usuario
(
    titulo_eleitoral bigint not null,
    unidade_codigo   bigint,
    ramal            varchar(20),
    email            varchar(255),
    nome             varchar(255),
    primary key (titulo_eleitoral)
);

create table if not exists sgc.unidade
(
    codigo                  bigint generated by default as identity,
    titular_titulo          bigint,
    unidade_superior_codigo bigint,
    sigla                   varchar(20),
    situacao                varchar(20) check (situacao in ('ATIVA', 'INATIVA')),
    tipo                    varchar(20) check (tipo in ('OPERACIONAL', 'INTERMEDIARIA', 'INTEROPERACIONAL', 'ADMINISTRATIVA')),
    nome                    varchar(255),
    primary key (codigo)
);

create table if not exists sgc.processo
(
    codigo           bigint generated by default as identity,
    data_criacao     timestamp(6),
    data_finalizacao timestamp(6),
    data_limite      timestamp(6),
    situacao         varchar(20) check (situacao in ('CRIADO', 'EM_ANDAMENTO', 'FINALIZADO')),
    tipo             varchar(20) check (tipo in ('MAPEAMENTO', 'REVISAO', 'DIAGNOSTICO')),
    descricao        varchar(255),
    primary key (codigo)
);

create table if not exists sgc.mapa
(
    sugestoes_apresentadas       boolean,
    codigo                       bigint generated by default as identity,
    data_hora_disponibilizado    timestamp(6),
    data_hora_homologado         timestamp(6),
    unidade_codigo               bigint,
    observacoes_disponibilizacao varchar(1000),
    sugestoes                    TEXT,
    primary key (codigo)
);

create table if not exists sgc.subprocesso
(
    codigo             bigint generated by default as identity,
    data_limite_etapa1 timestamp(6),
    data_limite_etapa2 timestamp(6),
    data_fim_etapa1    timestamp(6),
    data_fim_etapa2    timestamp(6),
    mapa_codigo        bigint,
    processo_codigo    bigint,
    unidade_codigo     bigint,
    situacao_id        varchar(50) check (situacao_id in ('NAO_INICIADO', 'CADASTRO_EM_ANDAMENTO', 'CADASTRO_DISPONIBILIZADO', 'CADASTRO_HOMOLOGADO', 'MAPA_CRIADO', 'MAPA_DISPONIBILIZADO', 'MAPA_COM_SUGESTOES', 'MAPA_VALIDADO', 'MAPA_HOMOLOGADO', 'REVISAO_CADASTRO_EM_ANDAMENTO', 'REVISAO_CADASTRO_DISPONIBILIZADA', 'REVISAO_CADASTRO_HOMOLOGADA', 'MAPA_AJUSTADO')),
    primary key (codigo)
);

create table if not exists sgc.alerta
(
    codigo                 bigint generated by default as identity,
    data_hora              timestamp(6),
    processo_codigo        bigint,
    unidade_destino_codigo bigint,
    unidade_origem_codigo  bigint,
    usuario_destino_titulo bigint,
    descricao              varchar(255),
    primary key (codigo)
);

create table if not exists sgc.alerta_usuario
(
    alerta_codigo            bigint not null,
    data_hora_leitura        timestamp(6),
    usuario_titulo_eleitoral bigint not null,
    primary key (alerta_codigo, usuario_titulo_eleitoral)
);

create table if not exists sgc.analise
(
    codigo                  bigint generated by default as identity,
    data_hora               timestamp(6),
    subprocesso_codigo      bigint,
    acao                    varchar(20) check (acao in ('ACEITE_MAPEAMENTO', 'DEVOLUCAO_MAPEAMENTO', 'ACEITE_REVISAO', 'DEVOLUCAO_REVISAO')),
    tipo                    varchar(20) check (tipo in ('CADASTRO', 'VALIDACAO')),
    unidade_sigla           varchar(30),
    analista_usuario_titulo varchar(50),
    motivo                  varchar(500),
    observacoes             varchar(500),
    primary key (codigo)
);

create table if not exists sgc.atividade
(
    codigo      bigint generated by default as identity,
    mapa_codigo bigint,
    descricao   varchar(255),
    primary key (codigo)
);

create table if not exists sgc.atribuicao_temporaria
(
    codigo         bigint generated by default as identity,
    data_inicio    timestamp(6),
    data_termino   timestamp(6),
    unidade_codigo bigint,
    usuario_titulo bigint,
    justificativa  varchar(500),
    primary key (codigo)
);

create table if not exists sgc.competencia
(
    codigo      bigint generated by default as identity,
    mapa_codigo bigint,
    descricao   varchar(255),
    primary key (codigo)
);

create table if not exists sgc.competencia_atividade
(
    atividade_codigo   bigint not null,
    competencia_codigo bigint not null,
    primary key (atividade_codigo, competencia_codigo)
);

create table if not exists sgc.conhecimento
(
    atividade_codigo bigint,
    codigo           bigint generated by default as identity,
    descricao        varchar(255),
    primary key (codigo)
);

create table if not exists sgc.movimentacao
(
    codigo                 bigint generated by default as identity,
    data_hora              timestamp(6),
    subprocesso_codigo     bigint,
    unidade_destino_codigo bigint,
    unidade_origem_codigo  bigint,
    descricao              varchar(255),
    primary key (codigo)
);

create table if not exists sgc.notificacao
(
    codigo                 bigint generated by default as identity,
    data_hora              timestamp(6),
    subprocesso_codigo     bigint,
    unidade_destino_codigo bigint,
    unidade_origem_codigo  bigint,
    conteudo               varchar(500),
    primary key (codigo)
);

create table if not exists sgc.parametro
(
    codigo    bigint generated by default as identity,
    chave     varchar(50),
    descricao varchar(255),
    valor     varchar(255),
    primary key (codigo)
);

create table if not exists sgc.unidade_mapa
(
    codigo              bigint generated by default as identity,
    data_vigencia       timestamp(6),
    mapa_vigente_codigo bigint not null,
    unidade_codigo      bigint not null unique,
    primary key (codigo)
);

create table if not exists sgc.unidade_processo
(
    codigo                  bigint generated by default as identity,
    processo_codigo         bigint,
    unidade_codigo          bigint,
    unidade_superior_codigo bigint,
    titular_titulo          varchar(12),
    sigla                   varchar(20),
    situacao                varchar(20),
    tipo                    varchar(20) check (tipo in ('OPERACIONAL', 'INTERMEDIARIA', 'INTEROPERACIONAL', 'ADMINISTRATIVA')),
    nome                    varchar(255),
    primary key (codigo)
);

create table if not exists sgc.usuario_perfil
(
    usuario_titulo_eleitoral bigint not null,
    perfil                   varchar(255) check (perfil in ('ADMIN', 'GESTOR', 'CHEFE', 'SERVIDOR'))
);

create table if not exists sgc.vinculacao_unidade
(
    codigo                  bigint generated by default as identity,
    unidade_anterior_codigo bigint,
    unidade_atual_codigo    bigint,
    primary key (codigo)
);

-- Foreign Keys
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_administrador_usuario') THEN
        ALTER TABLE sgc.administrador ADD CONSTRAINT fk_administrador_usuario FOREIGN KEY (usuario_titulo) REFERENCES sgc.usuario;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_alerta_processo') THEN
        ALTER TABLE sgc.alerta ADD CONSTRAINT fk_alerta_processo FOREIGN KEY (processo_codigo) REFERENCES sgc.processo;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_alerta_unidade_destino') THEN
        ALTER TABLE sgc.alerta ADD CONSTRAINT fk_alerta_unidade_destino FOREIGN KEY (unidade_destino_codigo) REFERENCES sgc.unidade;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_alerta_unidade_origem') THEN
        ALTER TABLE sgc.alerta ADD CONSTRAINT fk_alerta_unidade_origem FOREIGN KEY (unidade_origem_codigo) REFERENCES sgc.unidade;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_alerta_usuario_destino') THEN
        ALTER TABLE sgc.alerta ADD CONSTRAINT fk_alerta_usuario_destino FOREIGN KEY (usuario_destino_titulo) REFERENCES sgc.usuario;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_alerta_usuario_alerta') THEN
        ALTER TABLE sgc.alerta_usuario ADD CONSTRAINT fk_alerta_usuario_alerta FOREIGN KEY (alerta_codigo) REFERENCES sgc.alerta;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_alerta_usuario_usuario') THEN
        ALTER TABLE sgc.alerta_usuario ADD CONSTRAINT fk_alerta_usuario_usuario FOREIGN KEY (usuario_titulo_eleitoral) REFERENCES sgc.usuario;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_analise_subprocesso') THEN
        ALTER TABLE sgc.analise ADD CONSTRAINT fk_analise_subprocesso FOREIGN KEY (subprocesso_codigo) REFERENCES sgc.subprocesso;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_atividade_mapa') THEN
        ALTER TABLE sgc.atividade ADD CONSTRAINT fk_atividade_mapa FOREIGN KEY (mapa_codigo) REFERENCES sgc.mapa;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_atribuicao_temporaria_unidade') THEN
        ALTER TABLE sgc.atribuicao_temporaria ADD CONSTRAINT fk_atribuicao_temporaria_unidade FOREIGN KEY (unidade_codigo) REFERENCES sgc.unidade;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_atribuicao_temporaria_usuario') THEN
        ALTER TABLE sgc.atribuicao_temporaria ADD CONSTRAINT fk_atribuicao_temporaria_usuario FOREIGN KEY (usuario_titulo) REFERENCES sgc.usuario;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_competencia_mapa') THEN
        ALTER TABLE sgc.competencia ADD CONSTRAINT fk_competencia_mapa FOREIGN KEY (mapa_codigo) REFERENCES sgc.mapa;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_competencia_atividade_atividade') THEN
        ALTER TABLE sgc.competencia_atividade ADD CONSTRAINT fk_competencia_atividade_atividade FOREIGN KEY (atividade_codigo) REFERENCES sgc.atividade;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_competencia_atividade_competencia') THEN
        ALTER TABLE sgc.competencia_atividade ADD CONSTRAINT fk_competencia_atividade_competencia FOREIGN KEY (competencia_codigo) REFERENCES sgc.competencia;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_conhecimento_atividade') THEN
        ALTER TABLE sgc.conhecimento ADD CONSTRAINT fk_conhecimento_atividade FOREIGN KEY (atividade_codigo) REFERENCES sgc.atividade;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mapa_unidade') THEN
        ALTER TABLE sgc.mapa ADD CONSTRAINT fk_mapa_unidade FOREIGN KEY (unidade_codigo) REFERENCES sgc.unidade;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_movimentacao_subprocesso') THEN
        ALTER TABLE sgc.movimentacao ADD CONSTRAINT fk_movimentacao_subprocesso FOREIGN KEY (subprocesso_codigo) REFERENCES sgc.subprocesso;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_movimentacao_unidade_destino') THEN
        ALTER TABLE sgc.movimentacao ADD CONSTRAINT fk_movimentacao_unidade_destino FOREIGN KEY (unidade_destino_codigo) REFERENCES sgc.unidade;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_movimentacao_unidade_origem') THEN
        ALTER TABLE sgc.movimentacao ADD CONSTRAINT fk_movimentacao_unidade_origem FOREIGN KEY (unidade_origem_codigo) REFERENCES sgc.unidade;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_notificacao_subprocesso') THEN
        ALTER TABLE sgc.notificacao ADD CONSTRAINT fk_notificacao_subprocesso FOREIGN KEY (subprocesso_codigo) REFERENCES sgc.subprocesso;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_notificacao_unidade_destino') THEN
        ALTER TABLE sgc.notificacao ADD CONSTRAINT fk_notificacao_unidade_destino FOREIGN KEY (unidade_destino_codigo) REFERENCES sgc.unidade;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_notificacao_unidade_origem') THEN
        ALTER TABLE sgc.notificacao ADD CONSTRAINT fk_notificacao_unidade_origem FOREIGN KEY (unidade_origem_codigo) REFERENCES sgc.unidade;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_subprocesso_mapa') THEN
        ALTER TABLE sgc.subprocesso ADD CONSTRAINT fk_subprocesso_mapa FOREIGN KEY (mapa_codigo) REFERENCES sgc.mapa;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_subprocesso_processo') THEN
        ALTER TABLE sgc.subprocesso ADD CONSTRAINT fk_subprocesso_processo FOREIGN KEY (processo_codigo) REFERENCES sgc.processo;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_subprocesso_unidade') THEN
        ALTER TABLE sgc.subprocesso ADD CONSTRAINT fk_subprocesso_unidade FOREIGN KEY (unidade_codigo) REFERENCES sgc.unidade;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_unidade_titular') THEN
        ALTER TABLE sgc.unidade ADD CONSTRAINT fk_unidade_titular FOREIGN KEY (titular_titulo) REFERENCES sgc.usuario;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_unidade_superior') THEN
        ALTER TABLE sgc.unidade ADD CONSTRAINT fk_unidade_superior FOREIGN KEY (unidade_superior_codigo) REFERENCES sgc.unidade;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_unidade_mapa_mapa_vigente') THEN
        ALTER TABLE sgc.unidade_mapa ADD CONSTRAINT fk_unidade_mapa_mapa_vigente FOREIGN KEY (mapa_vigente_codigo) REFERENCES sgc.mapa;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_unidade_mapa_unidade') THEN
        ALTER TABLE sgc.unidade_mapa ADD CONSTRAINT fk_unidade_mapa_unidade FOREIGN KEY (unidade_codigo) REFERENCES sgc.unidade;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_usuario_unidade') THEN
        ALTER TABLE sgc.usuario ADD CONSTRAINT fk_usuario_unidade FOREIGN KEY (unidade_codigo) REFERENCES sgc.unidade;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_usuario_perfil_usuario') THEN
        ALTER TABLE sgc.usuario_perfil ADD CONSTRAINT fk_usuario_perfil_usuario FOREIGN KEY (usuario_titulo_eleitoral) REFERENCES sgc.usuario;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_vinculacao_unidade_anterior') THEN
        ALTER TABLE sgc.vinculacao_unidade ADD CONSTRAINT fk_vinculacao_unidade_anterior FOREIGN KEY (unidade_anterior_codigo) REFERENCES sgc.unidade;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_vinculacao_unidade_atual') THEN
        ALTER TABLE sgc.vinculacao_unidade ADD CONSTRAINT fk_vinculacao_unidade_atual FOREIGN KEY (unidade_atual_codigo) REFERENCES sgc.unidade;
    END IF;
END $$;
