import type {PermissoesSubprocesso} from "@/types/tipos";

export const PERMISSOES_SUBPROCESSO_VAZIAS: PermissoesSubprocesso = {
    podeEditarCadastro: false,
    podeDisponibilizarCadastro: false,
    podeDevolverCadastro: false,
    podeAceitarCadastro: false,
    podeHomologarCadastro: false,
    podeEditarMapa: false,
    podeDisponibilizarMapa: false,
    podeValidarMapa: false,
    podeApresentarSugestoes: false,
    podeVerSugestoes: false,
    podeDevolverMapa: false,
    podeAceitarMapa: false,
    podeHomologarMapa: false,
    podeVisualizarImpacto: false,
    podeAlterarDataLimite: false,
    podeReabrirCadastro: false,
    podeReabrirRevisao: false,
    podeEnviarLembrete: false,
    mostrarExportacaoMapa: false,
    mostrarHistoricoAnaliseDiagnostico: false,
    podePreencherAutoavaliacao: false,
    podeCriarConsenso: false,
    podeConcluirDiagnostico: false,
    podeValidarDiagnostico: false,
    podeDevolverDiagnostico: false,
    podeHomologarDiagnostico: false,
    mesmaUnidade: false,
    habilitarAcessoCadastro: false,
    habilitarAcessoMapa: false,
    habilitarAcessoDiagnostico: false,
    habilitarEditarCadastro: false,
    habilitarDisponibilizarCadastro: false,
    habilitarDevolverCadastro: false,
    habilitarAceitarCadastro: false,
    habilitarHomologarCadastro: false,
    habilitarEditarMapa: false,
    habilitarDisponibilizarMapa: false,
    habilitarValidarMapa: false,
    habilitarApresentarSugestoes: false,
    habilitarDevolverMapa: false,
    habilitarAceitarMapa: false,
    habilitarHomologarMapa: false,
    habilitarAlterarDataLimite: false,
    habilitarReabrirCadastro: false,
    habilitarReabrirRevisao: false,
    habilitarEnviarLembrete: false,
    habilitarPreencherAutoavaliacao: false,
    habilitarCardConsenso: false,
    habilitarCardSituacaoCapacitacao: false,
    habilitarCriarConsenso: false,
    habilitarConcluirDiagnostico: false,
    habilitarValidarDiagnostico: false,
    habilitarDevolverDiagnostico: false,
    habilitarHomologarDiagnostico: false,
};

export function normalizarPermissoesSubprocesso(
    permissoes?: Partial<PermissoesSubprocesso> | null,
): PermissoesSubprocesso {
    return {
        ...PERMISSOES_SUBPROCESSO_VAZIAS,
        ...permissoes,
    };
}
